### ISSUE TITLE
how can I use this  in  comfyui ？

### ISSUE THREAD

**Issue by GeLi1989** [hako-mikan/sd-webui-lora-block-weight#101]
have a plan to  support  this  in  comfyui ？

**Comment by GeLi1989** [comment]
thanks  a  lot

**Comment by hako-mikan** [comment]
I don't now detail.
Is this node what you want?
https://github.com/comfyanonymous/ComfyUI/pull/303

**Comment by GeLi1989** [comment]
> 
Thank you for your answer.

It seems that this node cannot be used（not found it）

**Comment by hako-mikan** [comment]
https://github.com/ltdrdata/ComfyUI-Inspire-Pack
