### ISSUE TITLE
多输出？

### ISSUE THREAD

**Issue by henbucuoshanghai** [hako-mikan/sd-webui-lora-block-weight#105]
你好，请问lora和unet的输出 均是很多层的输出？然后把对应层的求和 加起来？具体代码在哪呢？感谢

**Comment by hako-mikan** [comment]
English or Japanese please.

**Comment by henbucuoshanghai** [comment]
the output of the  original sd unet has only  one layer? or many layers?where is the code?
the output of the lora has  17 layers?  or?

**Comment by hako-mikan** [comment]
If the layer you're referring to represents 26 blocks, then it depends on the type of LoRA.
As written in the README, there are layers from 17 to 26, and within them, there are several smaller elements.

**Comment by henbucuoshanghai** [comment]
very kind answer,where is the code? 17-26layers?&nbsp; &nbsp;output?

**Comment by hako-mikan** [comment]
def to26(ratios):
    ids = BLOCKIDS[BLOCKNUMS.index(len(ratios))]
    output = [0]*26
    for i, id in enumerate(ids):
        output[BLOCKID26.index(id)] = ratios[i]
    return output
