### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by intheair1987** [hako-mikan/sd-webui-lora-block-weight#106]
Hi, I installed it in the Extensions tab and restarted the UI, but it's looking strange in the UI. For example, in txt2img, It appears in the area where you can find ControlNet and other extensions (I think this is normal), but it also appears in the "Scripts" dropdown list, and it appears for the third time at the bottom below the dropdown list (but I selected "none" in the dropdown list). Right after installation, the "activate" checkbox is checked by default (I don't think this is normal?). Lastly, no matter what I write in the prompts, I don't see any effects. Could you please help? Thanks!

**Comment by ultrasoniczrq** [comment]
My problem is exactly the same as yours

**Comment by hako-mikan** [comment]
https://github.com/hako-mikan/sd-webui-lora-block-weight#guide-for-api-users
When you enable API mode and use the UI, two extensions will appear. Please use the one on the bottom. The default presets can be used for presets. If you want to use your own presets, you can either edit the preset file or use the following format for the data passed to the API.
