### ISSUE TITLE
could not convert string to float

### ISSUE THREAD

**Issue by brightcxy** [hako-mikan/sd-webui-lora-block-weight#107]
I use  <lora:fairycore:0.5:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1> as my prompt, but lora block weight doesn't work:

LoRA Block weight (lora): fairycore: 0.5 x [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0]
nets
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001E4E758EE90>]: ValueError
Traceback (most recent call last):
  File "D:\sd\sd-webui-aki\sd-webui-aki-v4.10\modules\extra_networks.py", line 104, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\sd\sd-webui-aki\sd-webui-aki-v4.10\extensions-builtin\Lora\extra_networks_lora.py", line 28, in activate
    unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier
ValueError: could not convert string to float: '1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

LoRA Block weight (lora): fairycore: 0.5 x [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0]
nets

**Comment by anonCantCode** [comment]
Seems to be an issue with the latest webui version.

**Comment by hako-mikan** [comment]
To use in web-ui 1.5, use following syntax

<lora:"lora name":1:lbw=IN02>
<lora:"lora name":1:lbw=1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0>

https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/73
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/78
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/93
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/98
https://github.com/hako-mikan/sd-webui-lora-block-weight#updates%E6%9B%B4%E6%96%B0%E6%83%85%E5%A0%B1

**Comment by brightcxy** [comment]
It works! thank you!
