### ISSUE TITLE
ValueError: could not convert string to float: 'ALL0.5'

### ISSUE THREAD

**Issue by lost9999** [hako-mikan/sd-webui-lora-block-weight#109]
LoRA Block weight (lora): frd: 1.4 x [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
nets
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x0000025026A7E1D0>]: ValueError
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\sd-webui-aki-v4\extensions-builtin\Lora\extra_networks_lora.py", line 33, in activate
    unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier
ValueError: could not convert string to float: 'ALL0.5'

**Comment by hako-mikan** [comment]
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/73
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/78
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/93
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/98
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/107
https://github.com/hako-mikan/sd-webui-lora-block-weight#updates%E6%9B%B4%E6%96%B0%E6%83%85%E5%A0%B1

**Comment by lost9999** [comment]
> #73 #78 #93 #98 #107 https:github.com/hako-mikan/sd-webui-lora-block-weight#updates%E6%9B%B4%E6%96%B0%E6%83%85%E5%A0%B1

thanks，it works
