### ISSUE TITLE
Bug？: 「lbwpresets.txt' が見つかりません。」と出る。

### ISSUE THREAD

**Issue by NaokiSato102** [hako-mikan/sd-webui-lora-block-weight#11]
セーブプリセットを一度以上押さないと現れないようです。
最初から配置するようにするか、そうである旨を警告できるようにしていただけるとほかの人が助かると思います。

**Comment by hako-mikan** [comment]
ファイルが存在しない場合自動的に作成されるように修正しました。報告・提案ありがとうございます。

**Comment by NaokiSato102** [comment]
こちらこそありがとうございました。
