### ISSUE TITLE
What is the BASE block in the LoRA?

### ISSUE THREAD

**Issue by OwenTruong** [hako-mikan/sd-webui-lora-block-weight#110]
I thought the U-net only consisted of IN, MID and OUT blocks. What is the BASE block (is it the text encoder?) and what is the recommended way to train the BASE block? I am not able to see that setting in kohya_ss.

**Comment by hako-mikan** [comment]
Base refers to the Text Encoder. 
I don't have knowledge about training, so I can't offer you any advice.

**Comment by OwenTruong** [comment]
Thanks for the quick response!

I have another question though. When I set the encoder strength to 0 in lora:A-Lora:1:**0**, it gave me a very different results from <lora:A-Lora:1:**0**, 1,1,1,1,1,1, 1, 1,1,1,1,1,1,1,1,1>. Is there a reason why?

**Comment by hako-mikan** [comment]
First parameter is weight of the text encoder.
`<lora:A-Lora:0:1>` is same to `<lora:A-Lora:1:0, 1,1,1,1,1,1, 1, 1,1,1,1,1,1,1,1,1>`
https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

**Comment by hako-mikan** [comment]
The degree of effectiveness largely depends on the setting of training. 
With LoRA, which has been trained with many tags, TextEncoder is likely to work well.
On the other hand, the opposite can be said for styles LoRA that have not trained with TextEncoder.
