### ISSUE TITLE
XYZ plot - Effective Block Analyzer  bugged

### ISSUE THREAD

**Issue by sd2530615** [hako-mikan/sd-webui-lora-block-weight#115]
it works fine until i checked 'change X-Y' button, The 'Diff' tab shows wrong images(much like origin output image not the diff) instead of black and white things.

**Comment by Usak0428** [comment]
Yes, this is the same problem I am having.
The correct weights are applied to each image, but there is a problem with the output result of the grid image.

**Comment by QJieWang** [comment]
use `git checkout  3d226913c161032e5`  to roll back code to  Aug 10 can use this extention.

**Comment by hako-mikan** [comment]
Thanks reporting, fixed.
