### ISSUE TITLE
Repeated loading

### ISSUE THREAD

**Issue by yanghuihuang** [hako-mikan/sd-webui-lora-block-weight#116]
sd_webui：1.6.0
sd_webui_lora_block_weight: 2023.10.4

![image](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/53297778/cea1065e-042e-488a-9050-741201607b68)

**Comment by hako-mikan** [comment]
https://github.com/hako-mikan/sd-webui-lora-block-weight#regular-usage
`When you enable API mode and use the UI, two extensions will appear. Please use the one on the bottom.`

**Comment by yanghuihuang** [comment]
> https://github.com/hako-mikan/sd-webui-lora-block-weight#regular-usage `When you enable API mode and use the UI, two extensions will appear. Please use the one on the bottom.`

Thank you so much
