### ISSUE TITLE
Extension Fails to Function  When lora_in_memory_limit in WebUI is Not 0

### ISSUE THREAD

**Issue by yankuan66** [hako-mikan/sd-webui-lora-block-weight#117]
When I set lora_in_memory_limit to 5, this module only works once when opening a new webpage, and subsequent parameter changes do not result in any image changes. Continuing testing, I found that setting lora_in_memory_limit to 1 causes this extension to work abnormally.
![image](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/112066518/1d37b854-e675-45d7-96ea-1c446b3277b6)

Even when all parameters are set to 9, the image remains unchanged.

When lora_in_memory_limit is set to 0, it works properly. If all parameters are set to 9, the image becomes extremely terrifying; here, I've set the parameters to 1.
![image](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/112066518/ffebfb73-a30b-4395-904b-84d139a11fe2)

Similar issues were mentioned in a previous issue: https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/30, and the author claimed they were resolved, so I assume this is a new problem.

By the way, I've tested the previously suggested solution from the earlier issue (modifying the weight of Lora) when lora_in_memory_limit is set to 1, but it still doesn't seem to work correctly; the generated images have only minor changes.

![image](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/112066518/294ce0d3-436a-4a3f-a9b4-3cbd7dd5efde)

**Comment by hako-mikan** [comment]
Thanks reporting, fixed.
