### ISSUE TITLE
I'm about to give up

### ISSUE THREAD

**Issue by vjleoliu** [hako-mikan/sd-webui-lora-block-weight#118]
Whether I use <lora:"lora name":1:1:lbw=IN02> or <lora:"lora name":1:1:lbw=1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0> it's the same as <lora:"lora name":1>

Can someone tell me what the hell is going on here!!!

**Comment by yankuan66** [comment]
you should set lora_in_memory_limit to 0

**Comment by vjleoliu** [comment]
What's that?Where should I find it?

**Comment by yankuan66** [comment]
> What's that?Where should I find it?

You could add lora_in_memory_limit into Quicksettings list and reload ui to set it. Or you could search "Number of Lora networks to keep cached in memory" and set it to 0.
If it is already 0, I'm sorry I don't know how to fix.

**Comment by vjleoliu** [comment]
Thank you for your guidance.

**Comment by vjleoliu** [comment]
Do you use the same instructions for model merging?

**Comment by hako-mikan** [comment]
If you input <lora:"lora name":1:1:lbw=IN02>in prompt.
You can extract merge ratio in sueprmerger.
Use "get from prompt" button.
