### ISSUE TITLE
<lyco:"lora name":1:1:lbw=IN02>             what  is  :1:1

### ISSUE THREAD

**Issue by bihailantian655** [hako-mikan/sd-webui-lora-block-weight#119]
<lyco:"lora name":1:1:lbw=IN02>  (a1111-sd-webui-lycoris, web-ui 1.5 or later)

lora name":1:1

I am very confused

What  does  The  First  "1" values following "lora" are controlling . 

IF I  change  The first "1" value, although it produces data changes in the console, 

but  it  does not significantly affect the resulting image. 

However, when I  change the second value, I can clearly see visible changes in the generated image.

**Comment by bihailantian655** [comment]
text encode weight

**Comment by hako-mikan** [comment]
https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris#arguments

**Comment by bihailantian655** [comment]
thank you
