### ISSUE TITLE
About the impact on model merging

### ISSUE THREAD

**Issue by vjleoliu** [hako-mikan/sd-webui-lora-block-weight#120]
Refer to the format of <lora:"lora name":1:1:lbw=IN02> in the tex2img, and whether to do the same in the model merge ?
for example
lora name:1:lbw=IN02
like this ?

**Comment by hako-mikan** [comment]
If you input  <lora:"lora name":1:1:lbw=IN02>in prompt.
You can extract merge ratio in sueprmerger.
Use "get from prompt" button.
