### ISSUE TITLE
weight value Error always like value 1

### ISSUE THREAD

**Issue by WS-HS** [hako-mikan/sd-webui-lora-block-weight#126]
UI = A1111 Web-UI 1.6
u:?= lora weight value

Please compare these two xyz output pictures.
https://imgur.com/a/LeTPLQb
```
<lora:u:0:lbw=NONE> 
X/Y/Z plot
X 
Prompt S/R u:0,u:1,u:0.5
Y
Prompt S/R :lbw=NONE,:lbw=ALL,:lbw=XXX,
```

if use sd-webui-lora-block-weight 
like:
`<lora:u:1:lbw=NONE> <lora:u:1:lbw=ALL> `
`<lora:u:0:lbw=ALL>` etc...

CMD window has message:
`LoRA Block weight (lora):u: 0.5 x [0.0, 0.0, 0.0, 0.4, 0.5, 0.6, 0.7, 1.0, 1.0, 1.0, 0.8, 0.6, 0.5, 0.4, 0.0, 0.0, 0.0]`
or
`1 x 0,0,0,0,0,0,...........`
`0.3 x 0,0,1,0,0,0,...........`
`0.5 x 0,0,0,1,0,0,...........`
but not real work （1x or 0.5x or 0.3x not calculated ,  all ＝1x）
lora weight  It actually always looks like using 1

but 
if not use sd-webui-lora-block-weight 
like:
`<lora:u:0> <lora:u:0.5> <lora:u:1> `
This situation is normal output.
*like PIC2 last ROW

maybe , The calculated variables are not passed in correctly? 
Or are raw, uncomputed variables passed in?

**Comment by WS-HS** [comment]
X/Y/Z plot ser

```
<lora:u:0:lbw=NONE> face 
```
* u is lora name, you need use your lora name

```
X/Y/Z plot
X 
Prompt S/R u:0,u:1,u:0.5
Y
Prompt S/R :lbw=NONE,:lbw=ALL,:lbw=XXX,
```
* XXX you can use other , like OUTD

**Comment by WS-HS** [comment]
I removed other extensions about Lora,
Then it worked normally,
There may be a conflict with other extensions.
I suspect there is a conflict with Dynamic Lora Weights, but I'm not sure.

If anyone has the same error, please remove other extensions about Lora. Maybe it will work normally.

**Comment by hako-mikan** [comment]
Where is the notation such as "u:0" recommended? The only similar notations I am familiar with are:

1. `<lora:Model:1:0.5:13>`
2. `<lora:Model:1:0.5:dyn=13>`
3. `<lora:Model:1:unet=0.5:dyn=13>`
https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris#arguments

**Comment by WS-HS** [comment]
ok I’ve seen it and understood it,
Therefore, it is currently recommended to ignore the control of A1111 WenUi and always set it to <:1>
But use the second number <:1:0.5> to control the weight?
Sorry I just noticed this now
Thanks you.

**Comment by WS-HS** [comment]
I tried it, but I don’t quite understand the specific impact of "te, unet, and dyn" on the screen. Can you tell me the main difference in impact, or which one should be adjusted under what circumstances? Because I want to understand how to control it correctly.
Or, are there any articles you can recommend reading to understand the difference in their impact on the picture?
Thanks for making this extension, it's probably my most used extension :)

**Comment by hako-mikan** [comment]
`1:1` indicates the strength of unet and textencoder respectively, which corresponds to the `BASE` and `IN-OUT `layers in LoRA Block Weight. 
That is, 1:1 means the same as a sequence of 
`1,1,1,1,1,1,1,1...1`. 
If it is set to 0.5:1, it is the same as 
`0.5,1,1,1,1,...1`, 
and 1:0.5 is the same as 
`1,0.5,0.5,0.5....0.5`. 
Typically, both are set to 1, and it is easier to configure the weights on the LoRA Block Weight side.

**Comment by WS-HS** [comment]
THX. :)
So that's how it is, then I understand,
```
0.5:0.7 = lbw=0.5,0.7,0.7,0.7,0.7,0.7,0.7,0.7,0.7,0.7.....
0.1:0.5 = lbw=0.1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5.....
```
is this correct?

and . So how should we understand this part [` dyn `] more correctly?

**Comment by hako-mikan** [comment]
If you are using with LoRa Control - Dynamic Weights Controller, fixed.
