### ISSUE TITLE
Cannot apply LyCORIS with web-ui 1.5 or later

### ISSUE THREAD

**Issue by UuuNyaa** [hako-mikan/sd-webui-lora-block-weight#130]
In my environment, specifying `w_norm` property of `NetworkModuleNorm` solved the problem.

```diff
diff --git a/scripts/lora_block_weight.py b/scripts/lora_block_weight.py
index 760af3e..3dc999e 100644
--- a/scripts/lora_block_weight.py
+++ b/scripts/lora_block_weight.py
@@ -909,6 +909,7 @@ LORAANDSOON = {
     "LycoKronModule" : "w1",
     "NetworkModuleLokr": "w1",
     "NetworkModuleGLora": "w1a",
+    "NetworkModuleNorm": "w_norm",^M
 }
 
 def hyphener(t):
```

see: [network_norm.py#L16](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/4afaaf8a020c1df457bcf7250cb1c7f609699fa7/extensions-builtin/Lora/network_norm.py#L16)

**Comment by cyber-meow** [comment]
I can confirm this. This happens to networks for which train_norm are set to True.

**Comment by hako-mikan** [comment]
Thanks! Added to script.

**Comment by UuuNyaa** [comment]
@cyber-meow @hako-mikan 
Thank you for your efforts 😀
