### ISSUE TITLE
There are two LoRA Block Weight interfaces

### ISSUE THREAD

**Issue by wangwenqiao666** [hako-mikan/sd-webui-lora-block-weight#132]
After I installed the LoRA Block Weight, two interfaces appeared on the WEBUI。
![CB4F_`IRAZQ8I$61NX)N403](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/55267900/ba467210-ad4b-4975-92ae-3e62e87663d2)

But I only got one LoRA Block Weight
![KUDT`G 01X6{3~L7E~XVJF3](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/55267900/4a6fd139-16a0-4a9b-86cb-ae98c56f4aee)

**Comment by hako-mikan** [comment]
https://github.com/hako-mikan/sd-webui-lora-block-weight#guide-for-api-users
When you enable API mode and use the UI, two extensions will appear. Please use the one on the bottom. The default presets can be used for presets. If you want to use your own presets, you can either edit the preset file or use the following format for the data passed to the API.
