### ISSUE TITLE
UnicodeDecodeError: 'cp932' codec can't decode byte 0x8f

### ISSUE THREAD

**Issue by mirabarukaso** [hako-mikan/sd-webui-lora-block-weight#133]
Hello there,

I recently upgraded to the latest DEV branch of WebUI and then got this error on loading. It seems to be a simple Unicode conversion issue.

> *** Error loading script: lora_block_weight.py
>     Traceback (most recent call last):
>       File "F:\Stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
>         script_module = script_loading.load_module(scriptfile.path)
>       File "F:\Stable-diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
>         module_spec.loader.exec_module(module)
>       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>       File "F:\Stable-diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 30, in <module>
>         ui_config = json.load(json_file)
>       File "C:\Users\oOkami\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
>         return loads(fp.read(),
>     UnicodeDecodeError: 'cp932' codec can't decode byte 0x8f in position 54384: illegal multibyte sequence
> 
> ---

**The solution is simple, just replace "lora_block_weight.py" line 29 with the following code.**

From
`with open(cmd_opts.ui_config_file, 'r') as json_file:`
To
`with open(cmd_opts.ui_config_file, 'r', encoding="utf-8") as json_file:`

Regards

**Comment by hako-mikan** [comment]
Thanks, fixed.
