### ISSUE TITLE
How do i use elements?

### ISSUE THREAD

**Issue by Deathawaits4** [hako-mikan/sd-webui-lora-block-weight#134]
I have done a few tests and tried:

<lora:test:1:lbw=ALL:lbwe:ATTNDEEPON>
<lora:test:1:lbw=MIDD:lbwe:ATTNDEEPON>

and so forth

while they dont throw any errors, the output with lbwe is always the same as using only lbw, so im guessing the elements are ignored. The guide for elements is sadly not in english so i cant get a clue on how to use them.

**Comment by hako-mikan** [comment]
Thanks @torara46 for PR.
Fixed.
