### ISSUE TITLE
Support for OFT (and problem with bundle format)

### ISSUE THREAD

**Issue by cyber-meow** [hako-mikan/sd-webui-lora-block-weight#135]
OFT from [Controlling Text-to-Image Diffusion by Orthogonal Finetuning](https://arxiv.org/abs/2306.07280) is now working in webui after Kohaku fixes inference: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/14300

To make it work with OFT, I initially tried adding `"NetworkModuleOFT": "oft_blocks"` to `LORAANDSOON`. This runs but does not give the good results because OFT performs multiplication instead of addition.
What really fixes the problem is to add this in line 981
```
if ltype == "NetworkModuleOFT":
    oft_parameters = torch.nn.Parameter(getattr(lora.modules[key],LORAANDSOON[ltype]))
    I = torch.eye(oft_parameters.size()[1]).to(oft_parameters.device)
    oft_parameters = oft_parameters * ratio + I * (1-ratio)
    setattr(lora.modules[key], "oft_blocks", oft_parameters)
    set = True
```
Illustration:
![xyz_grid-0018-954588431](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/24396911/9299791f-ed33-47a9-b0ae-53940ae1829b)

This is from this OFT bundle: https://civitai.com/models/173081

---
By the way, the same issue for bundle format (i.e. an additional network with built-in embeddings) that I mentioned earlier for regional prompter https://github.com/hako-mikan/sd-webui-regional-prompter/issues/258 applies to LBW as well. This is not so critical but may worth some investigation if you have some time.

Thank you for the great plugins in any case.

**Comment by KohakuBlueleaf** [comment]
I recommend to modify scale instead of oft_blocks since kohya/lycoris have different implementation and have different math form for oft_blocks

**Comment by hako-mikan** [comment]
Fixed.
Thanks @KohakuBlueleaf for advice.

**Comment by cyber-meow** [comment]
Indeed. Both issues are solved now. Thanks.
