### ISSUE TITLE
Doesn't work with a1111-sd-webui-lycoris

### ISSUE THREAD

**Issue by Prince-Mars** [hako-mikan/sd-webui-lora-block-weight#137]
Due to a bug in the Regional Prompter, I had to re-enable support for a1111-sd-webui-lycoris.

But LBW does not work with a1111-sd-webui-lycoris. 
Generation proceeds fine, 
`LoRA Block weight (lyco): LYCONAME: 0.7 x [1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]`
but the result is the same as without LBW.

Downgraded to version of LBW [3eba732](https://github.com/hako-mikan/sd-webui-lora-block-weight/blob/3eba7323d60c12a0c4b4da50f5522d22ce11d02c/scripts/lora_block_weight.py) - it works.

How can I get the latest version to work?
Thanks.

P.S.
But I have new problem.
If you have lyco and lora in the same prompt, and use lbw with lora, then lyco does not seem to load. In order for everything to load, you need to delete the prompt, generate it, and enter the prompt again. I do not understand what the problem is.

**Comment by Prince-Mars** [comment]
And now I have problem with lora.... facepalm

**Comment by hako-mikan** [comment]
Are you using old version of Web-UI?

**Comment by Prince-Mars** [comment]
> Are you using old version of Web-UI?

I used version 1.6. Now I'm currently using version 1.7.
And the problem started with another error altogether - with a problem with lycoris support in the regional prompter: [NotImplementedError](https://github.com/hako-mikan/sd-webui-regional-prompter/issues/277#issuecomment-1856253887). Trying to go back to a separate lycoris support extension is a crutch.
And I haven't found a solution yet.

**Comment by KohakuBlueleaf** [comment]
> > Are you using old version of Web-UI?
> 
> I used version 1.6. Now I'm currently using version 1.7. And the problem started with another error altogether - with a problem with lycoris support in the regional prompter: [NotImplementedError](https://github.com/hako-mikan/sd-webui-regional-prompter/issues/277#issuecomment-1856253887). Trying to go back to a separate lycoris support extension is a crutch. And I haven't found a solution yet.

Plz disable or uninstall lycoris extension after sd-webui 1.5.0
