### ISSUE TITLE
Dosen't work with custom values

### ISSUE THREAD

**Issue by banMo88** [hako-mikan/sd-webui-lora-block-weight#139]
I define a set of custom values and name it NC. I write "NC:1,1,1,1,1,1,0,1,1,1,0.6,0,0,0,0,0,0" in the weight setting box.And"<lora:kamisato_ayaka:0.8:lbw=NC>" in the prompt box, but nothing happens. It generates the same as the picture without using this plugin. And there's no message in the console.

But it works when I use preset values like OUTD.For example,I write <lora:kamisato_ayaka:0.8:lbw=OUTD> , I can see the following measssage in the console:
"LoRA Block weight (lora): kamisato_ayaka: (Te:0.8,Unet:0.8) x [1.0, 0, 0.0, 0.0, 0, 0.0, 0.0, 0, 0.0, 0.0, 0, 0, 0, 0.0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]". And it did generate a different picture.

**Comment by hako-mikan** [comment]
If you are using with API option, you have two "LoRA Block Weight" in UI.
In this case, set preset in second "LoRA Block Weight".

**Comment by banMo88** [comment]
ok thanks
