### ISSUE TITLE
AttributeError: 'Network' object has no attribute 'bundle_embeddings'

### ISSUE THREAD

**Issue by YondSun** [hako-mikan/sd-webui-lora-block-weight#140]
*** Error running postprocess: D:\AI\sd-webui-aki-v4.5\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "D:\AI\sd-webui-aki-v4.5\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\AI\sd-webui-aki-v4.5\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 391, in postprocess
        for emb_name, embedding in net.bundle_embeddings.items():
    AttributeError: 'Network' object has no attribute 'bundle_embeddings'
    
没有搜到相关信息，不知道这个报错是什么意思，以及我找了lora_block_weight.py和scripts.py，没有找到Network类在哪…
I couldn't find any relevant information, and I don't understand what this error means. Also, I checked both lora_block_weight.py and scripts.py but couldn't find where the Network class is defined..

**Comment by hako-mikan** [comment]
Fixed.

**Comment by YondSun** [comment]
Thank you.
