### ISSUE TITLE
LBW Issue on A1111 v1.4.0 and Lower

### ISSUE THREAD

**Issue by ddoscv** [hako-mikan/sd-webui-lora-block-weight#146]
Hi, I recently installed A1111 v1.4.0 and installed the LBW extension through "Install from URL" using the [github page](https://github.com/hako-mikan/sd-webui-lora-block-weight). As far as I know, the changes on how you use LBW started at A1111 v1.5 and later versions, from a simple <lora:name:1:OUTD> to a longer <lora:name:1:lbw=OUTD>, hence why I installed v1.4.0 (Correct me if I'm wrong with this one).

So, the problem is that using <lora:name:1:OUTD> on v1.4.0 doesn't seem to work and I was getting the error:
"unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier ValueError: could not convert string to float: 'OUTD'"
If this issue on v1.4.0 is "normal" then okay, I understand and let's move on.

I also downgraded to v1.3.0 and v1.2.0 but I was still getting the same error. But here is the weird part--since I was getting the error, I decided to delete the LBW extension manually from E:\stable-diffusion-webui\extensions, and THEN, copy-paste my much-older folder of LBW extension FROM my A1111 v1.1 which is installed in a different folder instead. And somehow the issue was resolved even I reverted back to v1.4.0, I wasn't getting the error anymore and I was able to use <lora:name:1:OUTD> again which I couldn't previously.

Folder size in comparison of the LBW extension folder I used:
1. https://puu.sh/JYE5Z/d8245929c3.jpg This is "Install from URL" which was giving me problems. Also the folder name is "sd-webui-lora-block-weight"
2. https://puu.sh/JYE69/ce86c439a1.jpg This is my old one that I also have in my A1111 v1.1 installed in a different folder. The folder name of  this one is "sd-webui-lora-block-weight-main" which is also not fully detected in the "extensions" tab in webui unlike the others with URL and version

No, I'm not really in need of help or having problems for now. I just find this issue "weird" so I thought I'd let you know. Thank you for this amazing extension :)

**Comment by hako-mikan** [comment]
In this case, the version of the web UI is irrelevant. Regardless of the web UI version, the notation lbw= is required for the latest LoRA Block Weight.
