### ISSUE TITLE
AttributeError: 'ImageDraw' object has no attribute 'multiline_textsize'. Did you mean: 'multiline_text'?

### ISSUE THREAD

**Issue by lemoneder** [hako-mikan/sd-webui-lora-block-weight#149]
XYZ、Block analyzerいずれも画像のグリッド表示ができませんでした。
バージョンは最新のものをいれています。

---
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:06<00:00,  4.75it/s]
X:Original Weights, ALL,Y: none,, Z:none,, base:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 (10/10)
Skipping generation of duplicate base:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
*** Error completing request
*** Arguments: ('task(edlddjx0wyqsyhk)', '1girl,solo,black,twintail,two side up,very long hair,pink hair,looking at viewer,purple eyes,masterpiece,huge breasts,bed,demon girl,bedroom,night,sitting,black bikini,from below,<lora:marked2_1-000002:1:1:lbw=XYZ>,', 'nsfw,lowres,bad anatomy,bad hands,text,error,missing fingers,extra digit,fewer digits,cropped,worst quality,low quality,normal quality,jpeg artifacts,signature,watermark,username,blurry,artist name,', [], 30, 'DDIM', 1, 1, 7, 1024, 1440, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x0000024CFA198C70>, 0, False, '', 0.8, None, False, -1, 0, 0, 0, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 3072, 192, True, True, True, False, False, '', 0.5, True, False, '', 'Lerp', False, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 1, 'Original Weights', 'NONE,ALL,INS,IND,INALL,MIDD,OUTD,OUTS,OUTALL,ALL', 'none', '', 'none', '', '2,0', '12ALL', 1.0, 'black', '20', True, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, 5, 'all', 'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', '20', 'all', 'all', 'all', 'all', 0, '', [], False, True) {}
    Traceback (most recent call last):
      File "C:\sd2\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\sd2\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\sd2\webui\modules\txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "C:\sd2\webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 955, in newrun
        processed = script.run(p, *script_args)
      File "C:\sd2\webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 652, in run
        grids.append(smakegrid(images,xst,yst,origin,p))
      File "C:\sd2\webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 908, in smakegrid
        grid = images.draw_grid_annotations(grid,w, h, hor_texts, ver_texts)
      File "C:\sd2\webui\modules\images.py", line 218, in draw_grid_annotations
        draw_texts(d, x, y, hor_texts[col], fnt, fontsize)
      File "C:\sd2\webui\modules\images.py", line 161, in draw_texts
        while drawing.multiline_textsize(line.text, font=fnt)[0] > line.allowed_width and fontsize > 0:
    AttributeError: 'ImageDraw' object has no attribute 'multiline_textsize'. Did you mean: 'multiline_text'?

**Comment by hako-mikan** [comment]
お使いの環境にインストールされているpillowというモジュールのバージョンの問題のようです。
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13665

**Comment by lemoneder** [comment]
ありがとうございます。
初歩的な質問で申し訳ないのですが、pillowのバージョンを固定するにはどうすればよろしいでしょうか。
webui直下のrequirements_versions.txtにはPillow==9.5.0の記載があるのですが、Pillow-10.1.0.dist-infoがインストールされてしまいます。。

**Comment by lemoneder** [comment]
自己解決しました
layerdeviderの要求が9.4.0で競合していたためか最新の10.2.0がインストールされたようです。
layerdeviderを抜いたところ9.5がダウンロードされ正常に出力されました。
