### ISSUE TITLE
XYZ plot does not work

### ISSUE THREAD

**Issue by za-wa-n-go** [hako-mikan/sd-webui-lora-block-weight#15]
The default XYZplot works, but this one does not.
Generate will generate one piece and that's it.
I am trying with the latest updated a1111.

**Comment by hako-mikan** [comment]
Hires.fix has not been supported in the past, but is now supported in the latest version. Please try it out.

**Comment by hako-mikan** [comment]
I tried it with the latest version and it did not reproduce for me. The XYZ plot for this script does not work correctly if anything is assumed to be selected in the script items.

**Comment by za-wa-n-go** [comment]
Scripts are not selected.
If I press Generate with Active checked, will it run?

**Comment by za-wa-n-go** [comment]
Sorry I missed typing <lora: "lora name":1:XYZ>.
