### ISSUE TITLE
同一LORAにstepstop構文をつけるとエラーが起こる

### ISSUE THREAD

**Issue by null0516** [hako-mikan/sd-webui-lora-block-weight#153]
![Screenshot - 2024-03-03 10 22 24](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/142399604/68d1fa7d-b7c2-4b1d-a167-efc22ee762d9)

<lora:BasketballGirls-08_1_CharOUTD_p:1.0:stop=35>,
<lora:BasketballGirls-08_1_CharOUTD_p:1.0:stop=35>

このように同じLORAにSTEP制御構文をつけると上画像のエラーが起こります。
片方のステップ数をズラしても起こりました。

使用環境はStableDiffusion a1111 1.7.0です。
Forgeで試したところ、エラーメッセージ自体は出ませんでしたが、環境が壊れ以後LBWを使わなくても絵がノイズだらけになってしまいました。

loractlではLORAの二重適用は出来ていたので、LBWでも出来るようになって欲しいです。

**Comment by hako-mikan** [comment]
同じプロンプト内に同じLoRAを2回使うと言うことですか？

**Comment by null0516** [comment]
そのとおりです。
同じLoRAを低強度で二回適応することで画質を劣化させずに効果を強められるのでよく使っています。

**Comment by hako-mikan** [comment]
修正されました。

**Comment by null0516** [comment]
ご対応ありがとうございます！
