### ISSUE TITLE
What is the difference between BASE and text encoder value? They generate different images.

### ISSUE THREAD

**Issue by diodiogod** [hako-mikan/sd-webui-lora-block-weight#156]
I'm really grateful for this extension and supermerger. Analyzing my SDXL Lora I get the BEST results reducing the effect of the trained lora text encoder and chopping some Unet blocks. With these settings: ```<lora:NAME:0.25:1:lbw=0.25,0,0,0,0,0,1,1,1,0,0.15,1>```  I get really great results.
I really wish I could merge my lora to fix or adjust the Text Encoder value TE and Unet value to these ones above. But I don't know if it is possible.

From your other responses here 
https://github.com/hako-mikan/sd-webui-supermerger/issues/281#issuecomment-1805428022
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/110#issuecomment-1708282404

You said that the BASE value is the same as this FIRST TE value on the LoRA. As if in 
<lora:name:X:Y> the X is the same as BASE. But it doesn't look like it when testing it.

I'll use this tank shirt Lora as an examples (this is not the one I want to merge though):
This is the normal 
<lora:NAME:1>
<img src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/160325160/af562d71-9ef8-46f0-bc12-a206d6b50611" width='155'>

I understand there is some kind of multiplication going on from the "first TE" to the "BASE". If I set zero on the first value like this:

```<lora:NAME:0:1:lbw=100,1,1,1,1,1,1,1,1,1,1,1>```  it doesn't affect the generation and is the same as both with zero
```<lora:NAME:0:1:lbw=0,1,1,1,1,1,1,1,1,1,1,1>```
```<lora:NAME:100:1:lbw=0,1,1,1,1,1,1,1,1,1,1,1>```  it does affect the generation and generate noise because of the high value, so its not a simple multiplication of the first TE to the BASE or else it would be the same as zero.

<img src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/160325160/065c49c1-554b-4c44-a42e-25ccad6a3acb" width='155'><img src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/160325160/80d04f27-5e6e-4d81-9dfd-651939f9ae2b" width='155'><img src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/160325160/2632e60d-733c-4891-82a9-3dd603656299" width='155'>

Now with 0.8 on the "first TE" (different seed and prompt):
```<lora:NAME:0.8:1:lbw=0,1,1,1,1,1,1,1,1,1,1,1>```       BASE 0: TE 1 affect the generation and crate image "N"
```<lora:NAME:0.8:1:lbw=0.5,1,1,1,1,1,1,1,1,1,1,1>```    BASE 0.5: it affect the generation and create a slightly altered image "Na" 
```<lora:NAME:0.5:1:lbw=0.8,1,1,1,1,1,1,1,1,1,1,1>```    BASE 0.8: it affect the generation and create a slightly altered image "Nb" but NOT "Na"
```<lora:NAME:0.5:1:lbw=0.5,1,1,1,1,1,1,1,1,1,1,1>```    BASE 0.5 and TE 0.5: it affect the generation and create a slightly altered image "Na" but NOT "Na" or "Nb"

So any positive value on any side will affect the generation and they are not interchangeable.
<img src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/160325160/09577fa9-e198-4ad8-ab26-356a7ef09714" width='155'><img src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/160325160/ee4177b4-8d82-46c6-b494-baed0ce7315a" width='155'><img src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/160325160/12d534f1-6c2b-4879-b4b1-86712e82a06d" width='155'><img src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/160325160/23c7d15f-54ff-43a3-b3c4-7f2035388904" width='155'>

So my questions are: 
1- how are they different? Are they adjusting the same thing?
2- Is it possible to create/adjust a Lora in supermerger to get a 0.25 on the "First TE" value and also adjust the rest of the Unet values?

This should be on supermerger github I guess, but you are also the author so, using supermerger with these options (only one LoRA):

```NAME:0.25:1:0.25,0,0,0,0,0,1,1,1,0,0.15,1```    doesn't work, it uses 0.25 to all blocks. > ERROR:Number of Blocks must be 12,17,20,26
```NAME:0.25:0.25,0,0,0,0,0,1,1,1,0,0.15,1```       It works but it doesn't look like the 0.25 meters at all. This is the same as using this
```NAME:1:0.25,0,0,0,0,0,1,1,1,0,0.15,1```            or this with weight 99
```NAME:99:0.25,0,0,0,0,0,1,1,1,0,0.15,1```
Looks like it ignores the strength.

the best way I could think of was adjusting using "lora block weight" (this is all on generation not after merging, I could not make it work with supermerger) the Unet in a way that I could just use the LoRA as 0.25 both for TE and UNET Like this:
```<lora:NAME:0.25:1:lbw=0.25,0,0,0,0,0,1,1,1,0,0.15,1>``` is very similar to this
```<lora:NAME:0.25:0.25:lbw=0.05,0,0,0,0,0.6,4,4,4,0,0.6,4>``` i multiplied everything by 4 and the BASE is a really low value, close to be divided by 4. It's the best I could do to get close to the Lora:0.25:1 with the blocks I wanted
<img src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/160325160/4a25581b-137a-4b8e-9eaf-acd5360c9ad2" width='155'><img src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/160325160/c3731350-a284-4b71-90f6-79c7c2a885c1" width='155'>

the same way:
```<lora:NAME:0.25:1:lbw=0.25,1,1,1,1,1,1,1,1,1,1,1>```      is very similar to this
```<lora:NAME:0.25:0.25:lbw=1,4,4,4,4,4,4,4,4,4,4,4>```      that is very similar to
```<lora:NAME:0.25:1>```
<img src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/160325160/e2cd9b9a-f857-47af-8c95-41ae7c0a81c5" width='155'><img src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/160325160/ed05fff7-f5db-4841-be73-91344e855261" width='155'><img src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/160325160/4fd893f4-ab18-4f45-8066-0d308d9cff66" width='155'>

But using on supermerger (NAME:0.25:1,4,4,4,4,4,4,4,4,4,4,4) don't work and has side effects because of such high values. They look similar on the generation but not after merge. If I merge this I get the lora to work if I use the merged lora in a very very small value like
```<lora:NewMergedNAME:0.08>```

**Comment by hako-mikan** [comment]
Yes. The values for BASE and Te are the same. This means that the results you tested should originally be the same. In fact, the results I tested were the same for the following three outcomes:

    Generated using lbw for `<lora:NAME:0.5:1:lbw=1,1,1,1,1,1,1,1,1,1,1,1>`
    Generated using lbw for `<lora:NAME:1:1:lbw=0.5,1,1,1,1,1,1,1,1,1,1,1>`
    Generated by merged model using ratio `lora:NAME:1:0.5,1,1,1,1,1,1,1,1,1,1,1`

This could be due to differences in the environment you are using. The handling of LoRA can vary significantly depending on the version of the web-ui and its settings, etc.

**Comment by diodiogod** [comment]
> Yes. The values for BASE and Te are the same. This means that the results you tested should originally be the same. In fact, the results I tested were the same for the following three outcomes:
> 
> ```
> Generated using lbw for `<lora:NAME:0.5:1:lbw=1,1,1,1,1,1,1,1,1,1,1,1>`
> Generated using lbw for `<lora:NAME:1:1:lbw=0.5,1,1,1,1,1,1,1,1,1,1,1>`
> Generated by merged model using ratio `lora:NAME:1:0.5,1,1,1,1,1,1,1,1,1,1,1`
> ```
> 
> This could be due to differences in the environment you are using. The handling of LoRA can vary significantly depending on the version of the web-ui and its settings, etc.

Oh my... I've just tested on my forge installation and you are correct. <lora:NAME:1000:1:lbw=0,1,1,1,1,1,1,1,1,1,1,1> did not make noise.
So I kept testing and now I think it's about SDXL. On Sd15 you are correct <lora:NAME:99:1:lbw=0,1,1,1,1,1,1,1,1,1,1,1> wont generate noise. It acts as Te:0
But with SDXL loras <lora:SDXLloraNAME:99:1:lbw=0,1,1,1,1,1,1,1,1,1,1,1> will generate noise. Would you try it? It happens both on Forge and on my automatic1111.

Anyway, thanks for the response. You extension is probably the most needed and amazing of all SD ones I use!

**Comment by hako-mikan** [comment]
Ah, you were right. 
Looks like the thing you mentioned did happen with XL. 
When I checked it out, it seems like it hadn't dealt with the second text encoder that was added to XL. 
Seems like the problem got missed initially because the XL LoRA's Text Encoder wasn't trained at the start. 
It's been sorted now. 
Thanks.
