### ISSUE TITLE
setting weights does not appear to work with API

### ISSUE THREAD

**Issue by Manaball123** [hako-mikan/sd-webui-lora-block-weight#16]
despite the prompts sent POST request in the api being identical to the one that is being is used in the webui, the latter writes a log in the cmd window saying that (LoRA Block weight :(lora name): [(weights here)] while the former does not, or, more notably, the end results of the 2 generations are very different despite other parameters being identical.
I would assume that this is caused by the tokenizer not properly parsing the weight list(i.e. the [1,1,1,1,1,0,0,0] or whatever) when the prompt is loaded from the API, and only takes effect when the prompts are loaded from the web ui.
Is there any way to work around this? If not, do you plan on making this possible?

**Comment by Manaball123** [comment]
In case I didn't do a good job at describing the issue, here's the TLDR version:
![image](https://user-images.githubusercontent.com/57663038/226339745-50e41d68-0e97-410d-89a1-db021d0e37c8.png)
The highlighted section(the weight adjusting thing) only takes effect when typed in the webui, and does not take effect when sent from the api.

**Comment by Manaball123** [comment]
For reference, here's the console output when it DOES work as intended.
![image](https://user-images.githubusercontent.com/57663038/226486208-bc7dab40-91af-48a9-81a6-24b77aba27e5.png)
As for the values in the LORA block weights tab(marked by the "1" in your screenshot), it somehow works after you delete a bunch of the other stuff from it(i.e. only leave INS in the textbox if you want that).
Again, this is all pretty inconsistent though. 
I would fork this and write something myself but unfortunately the codebase is pretty messy atm :(

**Comment by Manaball123** [comment]
I think I have a temporary fix for this.
By setting useblocks to true, and providing default args for loraratios, the correct args can be passed without the need of getting args from the ui.
I'll make a pr in a sec

**Comment by Manaball123** [comment]
On a side note, I feel like the codebase can probably need some reorganization as it is pretty hard to find out what's going on currently

**Comment by xxtyy** [comment]
How to call the weight function through the api
How do I pass parameters to enable this function?
can you help me？my friend

**Comment by hako-mikan** [comment]
If installed normally, this script is automatically turned on. I have tried it on API and it seems to work fine.

**Comment by Manaball123** [comment]
It should work if you just include the weight params in the prompt, though you can't pass in additional params through the api yet

**Comment by hako-mikan** [comment]
There are no commands to edit presets. Is it possible to edit a preset file directly?

**Comment by cream3344** [comment]
Can you provide the api code


> It should work if you just include the weight params in the prompt, though you can't pass in additional params through the api yet

Can you provide the api code

**Comment by hako-mikan** [comment]
The XYZ plot and Effective Block Analyzer are now usable through the API. Also, I have written a guide about the API.
