### ISSUE TITLE
Not sure I understand how Effective Block Analyzer works

### ISSUE THREAD

**Issue by maepopi** [hako-mikan/sd-webui-lora-block-weight#160]
Hey there,

Thank you for this very useful tool. I have trouble understanding what the Effective Block Analyzer does though. 

> " This function check which layers are working well. The effect of the block is visualized and quantified by setting the intensity of the other bocks to 1, decreasing the intensity of the block you want to examine, and taking the difference.
> 
> Range
> If you enter 0.5, 1, all initial values are set to 1, and only the target block is calculated as 0.5. Normally, 0.5 will make a difference, but some LoRAs may have difficulty making a difference, in which case, set 0.5 to 0 or a negative value."

If I understand correctly, in the resulting plot, "source" corresponds to all the blocks INCLUDING the target block being calculated at value 1, and the middle column, "0.5", corresponds to the output of all blocks INCLUDING the target block but the target block is calculated at 0.5. The first column, "diff", makes the difference between the two images, that is to say between:
- All blocks including the target block, all blocks at 1 ("source" column)
- All blocks excluding the target block are at 1, target block is at 0.5 (middle column)

Is that the correct interpretation?

Thank you

**Comment by hako-mikan** [comment]
Your are correct.
