### ISSUE TITLE
ID not found in list

### ISSUE THREAD

**Issue by maepopi** [hako-mikan/sd-webui-lora-block-weight#161]
Hello,

I have defined custom weights under the "Make weights" panel, so as to invert all the weights to 0 except the target block, instead of having all the blocks to 1. I have hit "reload presets", "save presets", I can see my new presets in the very first panel (see picture), but when I try the command

`<lora:1:1:lbw=XYZ>`

I have an error message saying my first weight (that I called INVBASE for BASE inverted) is not in list. 

I hereby join the images of my setup, can someone tell me what I'm doing wrong?

Thank you!
![brave_cYZM5W1AVw](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/35258413/0ca98578-1aa0-4fc4-a54c-d413af81a018)
![brave_MGKQG25QqQ](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/35258413/ed656e19-48c6-4330-ba4e-8435f6648a01)

**Comment by maepopi** [comment]
I'm sorry I got confused and eventually got the answer to my question : typing <lora:1:1:lbw=IN01> already guarantees that the only activated block is IN01, and all the others are at 0. So the XYZ plot already does its job when the values to change are the individual blocks themselves.

My brain got all tangled up, sorry for the stupid question!

**Comment by maepopi** [comment]
Hey everyone, I am reopening this question because after more testing, I realize my first insight was right : 

IN01 with target block at 0 corresponds to : 1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

I tried writing new inverted configurations, among them INVIN01 : :0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

But when I try using it, it is not recognize by the addon. So if someone has an idea what I'm doing wrong, I'm all ears!

Thanks

**Comment by hako-mikan** [comment]
The Block ID you selected for the Y-axis is a setting to specify options such as OUT01 or BASE. 
If what you want to specify is something like INVBASE, please select Original Weight.
