### ISSUE TITLE
完全に無反応

### ISSUE THREAD

**Issue by ecchikonro** [hako-mikan/sd-webui-lora-block-weight#166]
version: [v1.10.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/c19d04436496ab29ddca4758a792831ae41b31de)で、

タイトル通り生成時に反映されません。

アクティブにしたし、:1:lbw=XYZも入れたし、モデルを変えて試してみたし、loraも変えて試してみましたがうんともすんとも言わず、エラーすら出ません。

コンソールにlora block weightの文字すらありません。

入れ直してみましたがダメでした。
完全にお手上げです。

StabilityMatrixから使っています。

**Comment by hako-mikan** [comment]
どうやらStabilityMatrixを使用する場合、APIモードが自動的に有効になってしまい、意図せぬ動作をしてしまっている用です。パッケージ設定からAPIのオプションを外すことで意図した動作になるかと思います。
