### ISSUE TITLE
forge is renewed with gradio 4 so...

### ISSUE THREAD

**Issue by CoqueTornado** [hako-mikan/sd-webui-lora-block-weight#168]
any charming soul can upgrade this amazing extension to the new Flux Forge?

Somebody said:
"sd_hijack part required by lbw has been adjusted, which makes the latest version of forge incompatible with lbw."

Also is gradio 4 not gradio 3, so maybe that clue can help. 
----
いかなる魅力的な魂も、新しいFlux Forgeにこの素晴らしい拡張機能をアップグレードすることができます。

誰かが言った通り：
「lbwが要求するsd_hijackパートが調整されたため、最新のForgeがlbwと互換性がなくなりました。」

また、Gradio 4がGradio 3ではないというヒントも役立つかもしれません。

**Comment by diodiogod** [comment]
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/167#issuecomment-2335250910

**Comment by hako-mikan** [comment]
May be fixed in current version.
