### ISSUE TITLE
When installed as extension, txt file cannot be used

### ISSUE THREAD

**Issue by ClashSAN** [hako-mikan/sd-webui-lora-block-weight#2]
This is a great extension. I have few infos/guide on what lora blocks are doing, there is more independent research that has happened for unet. 

Maybe we can use this like an extension instead? the paths are set currently to look in custom scripts. 

Or maybe, Is this LoRA block merging feature possible to be added in https://github.com/hako-mikan/sd-webui-supermerger? 

(I'm sorry if maybe it's already added. It looked like its only for extracting lora's from models, choosing block weights, and saving as a file.)

**Comment by hako-mikan** [comment]
Thanks reporting and helping in issues in SuperMerger.

The preset files should be located in the web-ui/scripts folder, so I rewrote it to move it at starting. 
There is a reason for this: the supermerger also refers to this file, and I do not want the location of the preset files to change depending on where LoRA block Weight is installed.

Supermerger has the ability to convert loRAs with the ratio set in the LoRA block weight.
Which can be done by using "Merge LoRAs" in the LoRA tab in SuperMerger. 
This can also be applied to single LoRAs.
You can specify the blocks in which you want to weaken or strengthen the effect. 
For this purpose, I refer to the LoRA Block Weight file.

**Comment by ClashSAN** [comment]
Just checking, so, only this extension can apply (in block weight) LoRA's to your current model, without saving as a file, right? 

Thanks for the fix! Let me know if I'm mistaken.

**Comment by hako-mikan** [comment]
Yes. This extension only modifies the LoRA loading for image generation, it does not save it.
