### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by slashedstar** [hako-mikan/sd-webui-lora-block-weight#20]
Every time a image is generated with a lora a bit of memory leaks, eventually you get a out of memory error
With extension disabled (steady memory usage):
![image](https://user-images.githubusercontent.com/103432664/226429864-1f38800e-5832-4626-bea7-24df611b7484.png)
![image](https://user-images.githubusercontent.com/103432664/226431950-c48b1002-243c-4fda-8c23-4e3ec5d241ea.png)

With extension enabled (memory usage increases every time after you hit generate):
![image](https://user-images.githubusercontent.com/103432664/226429890-ff674c1d-fdfd-4a27-8d34-3aa9b026f40e.png)
![image](https://user-images.githubusercontent.com/103432664/226431415-246a63dd-7615-44d7-9d5c-1e993d869508.png)

To easily reproduce this you can set the resolution to 64x64, 1 step, and add a lora to the prompt, the bigger the lora the faster you will notice it.

**Comment by Manaball123** [comment]
Try adding a line under process(): (around line 200)
torch.cuda.empty_cache()
Note that I haven't extensively tested this, and this may lower your overall performance.
I am speculating that this is caused by the new LoRA being allocated(one with modified weights) not properly being freed after allocation.

**Comment by hako-mikan** [comment]
Thanks reporting. Added code to release memory. It improved in my environment, please try it.

**Comment by Daniel-Poke** [comment]
Okay, I'm not crazy, I thought this extension just used a high amount of memory so I turn it off when I am bulk generating, but those usage graphs show a definite climb in memory.

Thank you for reporting and thanks @hako-mikan for resolving (potentially). I will test this out also.

**Comment by slashedstar** [comment]
Yeah, its fixed after updating, thanks
