### ISSUE TITLE
Bug? Checkbox "Active" immediately below "LoRA Block Weight" and above "XYZ plot" doesn't do anything.

### ISSUE THREAD

**Issue by gryphus-crux** [hako-mikan/sd-webui-lora-block-weight#24]
Hello, I've found that this section doesn't seem to do anything:
![image](https://user-images.githubusercontent.com/128222225/227504737-f7d192de-b7bb-43bb-a714-28114dda331a.png)
I thought that the list in this box must match with the identifiers defined in the Weights setting box, but the extension works with no issues even if I clear everything in this box, and it does not have any effect if the box is checked or not. Should it be working differently? If not, what is the function of this box?

**Comment by hako-mikan** [comment]
Are there any errors in the command prompt?
If it is a problem with files using 2-byte characters, then the latest update has solved the problem.

**Comment by gryphus-crux** [comment]
Apologies - I've only been able to test it now as my GPU was not useable for some time. 
Thank you for the update, there was a change to LoRA code on webui side and I remember I had to roll back to a previous branch to use this extension. 
The extension now works fine, but unchecking the checkbox or deleting everything inside the 'active' box still generates output. Is this intentional?

**Comment by hako-mikan** [comment]
It is unintentional; it should not work if active is turned off. Is this the same in the latest version?
