### ISSUE TITLE
AttributeError: 'function' object has no attribute 'weight'

### ISSUE THREAD

**Issue by Kimdow220807** [hako-mikan/sd-webui-lora-block-weight#27]
HI,When I use it, an error message pops up:AttributeError: 'function' object has no attribute 'weight'

**Comment by AI-Casanova** [comment]
Same thing here.

**Comment by AI-Casanova** [comment]
Looks like an A1111 issue https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8977

**Comment by AI-Casanova** [comment]
Actually no, though I think it's related. 

If I use an in prompt LoRA normally, it works fine, but once I try block weight, it gives me the error, and it no longer works even without the extension.

**Comment by hako-mikan** [comment]
“There may be a problem with the web-ui update, so I’ll wait and see for a while. It’s troublesome if it overlaps with the main body fix.”

**Comment by hako-mikan** [comment]
There may be a problem with the web-ui update, so I’ll wait and see for a while. It’s troublesome if it overlaps with the main body fix. Also, have you tried the Locon update?

**Comment by OedoSoldier** [comment]
Yeah clearly WebUI changed the way it apply LoRA weight, this script need fix.

**Comment by girllover2154** [comment]
> Yeah clearly WebUI changed the way it applies LoRA weight, this script needs to be fixed.
> 
> Edit: I've fixed it: #28

How exactly? I tried it, and it's only giving me this f@cking "mat1 and mat2 shapes cannot be multiplied" error. In other words; either it doesn't work or you need to explain it better. Bye

**Comment by AI-Casanova** [comment]
Yo, why are you yelling at a dude that doesn't even own the repo, for trying to help fix a problem that wasn't even caused by anyone here?

Bye Felicia, indeed!

**Comment by girllover2154** [comment]
I apologize for my rudeness, it's just that frustrates to the core that things technically become unusable out of nothing, and I cannot find any factible solution to that. That's doesn't justify my behavior, but try to put yourself in my shoes; you're trying to do a very simple thing, and it suddenly becomes overly complicated for no reason just because of one stupid error, and worst of all there no way to fix that for the moment which is really irritating. Again, I apologize for my words, but to understand me why I act like that.

**Comment by AI-Casanova** [comment]
I understand the frustration, I have my own projects that are downstream of this one, that is downstream of A1111. 

Try to temper your frustration with the realization that this amazing bleeding edge technology is being brought to you for free, by a bunch of random anons, who genuinely want to make the space work better, but whose efforts aren't perfectly aligned.

**Comment by girllover2154** [comment]
Thanks for your words, and I'll try to let out my frustrations in a more constructive manner.

**Comment by hako-mikan** [comment]
Fixed. How about after that?

**Comment by girllover2154** [comment]
> Fixed. How about after that?

It's all better now, thanks. Also, sorry for my impatience and rudeness, should have done better. 😔

**Comment by hako-mikan** [comment]
I don't care. Enjoy!
