### ISSUE TITLE
Enhancement: ZYX Tag 

### ISSUE THREAD

**Issue by AI-Casanova** [hako-mikan/sd-webui-lora-block-weight#3]
It would be really nice to have a ZYX tag = 1 - XYZ
basically
`XYZ = 1,0.75,0.5,0.25...`
`ZYX = 0,0.25,0.5,0.75...`
Then when running grids, you could "fill in" blocks of LoRA1 with blocks of LoRA2

I am using this extension to search for LoRA merge settings for Supermerger.

**Comment by hako-mikan** [comment]
Is my understanding correct for the following functions? Here we have XYZ for Jordan_3 and ZYX for MagicLORA.
This feature has been added. Please try it out.

X:values, 0.25,Y: Block ID,IN05-OUT05, Z:none,, base:1,1,1,1,0.25,0.25,0.25,0.25,0.25,0.25,0.25,1,1,1,1,1,1 (2/5)
LoRA Block weight :Jordan_3: [1.0, 1.0, 1.0, 1.0, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
LoRA Block weight :MagicLORA: [0.0, 0.0, 0.0, 0.0, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

X:values, 0.5,Y: Block ID,IN05-OUT05, Z:none,, base:1,1,1,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,1,1,1,1,1,1 (3/5)
LoRA Block weight :Jordan_3: [1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
LoRA Block weight :MagicLORA: [0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

X:values, 0.75,Y: Block ID,IN05-OUT05, Z:none,, base:1,1,1,1,0.75,0.75,0.75,0.75,0.75,0.75,0.75,1,1,1,1,1,1 (4/5)
LoRA Block weight :Jordan_3: [1.0, 1.0, 1.0, 1.0, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
LoRA Block weight :MagicLORA: [0.0, 0.0, 0.0, 0.0, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

X:values, 1,Y: Block ID,IN05-OUT05, Z:none,, base:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 (5/5)
LoRA Block weight :Jordan_3: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
LoRA Block weight :MagicLORA: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

**Comment by hako-mikan** [comment]
Is my understanding correct for the following functions? Here XYZ for Jordan_3 and ZYX for MagicLORA.
This feature has been added. Please try it out.

X:values, 0.25,Y: Block ID,IN05-OUT05, Z:none,, base:1,1,1,1,0.25,0.25,0.25,0.25,0.25,0.25,0.25,1,1,1,1,1,1 (2/5)
LoRA Block weight :Jordan_3: [1.0, 1.0, 1.0, 1.0, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
LoRA Block weight :MagicLORA: [0.0, 0.0, 0.0, 0.0, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

X:values, 0.5,Y: Block ID,IN05-OUT05, Z:none,, base:1,1,1,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,1,1,1,1,1,1 (3/5)
LoRA Block weight :Jordan_3: [1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
LoRA Block weight :MagicLORA: [0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

X:values, 0.75,Y: Block ID,IN05-OUT05, Z:none,, base:1,1,1,1,0.75,0.75,0.75,0.75,0.75,0.75,0.75,1,1,1,1,1,1 (4/5)
LoRA Block weight :Jordan_3: [1.0, 1.0, 1.0, 1.0, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
LoRA Block weight :MagicLORA: [0.0, 0.0, 0.0, 0.0, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

X:values, 1,Y: Block ID,IN05-OUT05, Z:none,, base:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 (5/5)
LoRA Block weight :Jordan_3: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
LoRA Block weight :MagicLORA: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

**Comment by AI-Casanova** [comment]
That looks perfect, I can't wait to try it out tomorrow! Thank you for your quick response, you're awesome.

**Comment by AI-Casanova** [comment]
It's working wonderfully. You're the best!

**Comment by ruSauron** [comment]
Small problem with ZXY mode: XYZ plot only looks for tag XYZ in the query. If there is no XYZ tag in the query, the XYZ plot is not activated. You can get around this by adding another LoRA model with zero to the query. Example:
Doesn't work right now: `1girl, <lora:mylora:1:ZYX>`
Works: `1girl, <lora:mylora:1:ZYX> <lora:randomlora:0:XYZ>`

**Comment by hako-mikan** [comment]
Each value of ZYX is defined as 1-XYZ, so it will not work unless XYZ is defined.

You can activate only one block by inverting the value in the "Range" (for example 1,0) of "effective block analyzer".
