### ISSUE TITLE
LoRA block weight change takes NO EFFECT in new versions of stable diffusion webui

### ISSUE THREAD

**Issue by lwh9346** [hako-mikan/sd-webui-lora-block-weight#30]
### LoRA block weight change takes NO EFFECT after commit 80b26d2a of sd webui.

Here is the link to a commit: [80b26d2a commit](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/80b26d2a69617b75d2d01c1e6b7d11445815ed4d)

Commit message:
apply Lora by altering layer's weights instead of adding more calculations in forward()

### What's the problem?
First, generate an image with a lora prompt: `<lora:example:1:ALL>`->**img1**
Then, fix seed, and generate another image with a lora prompt: `<lora:example:1:NONE>`->**img2**
You will find that **img2** is the same as **img1**.❌
But if you change the multiplier of added lora, just a little bit: `<lora:example:0.99:NONE>`->**img3**
**img3** is the result that **img2** should be.✔

### So, why?
This commit changed the behaviour of the builtin lora extension. In previous versions, the lora is applied to model by adding a "lora forward" step in forward steps. After this commit, the lora is applied by altering layers' weights. **And the author add a cache mechanism to avoid applying lora every time.**

This change leads to a problem: 
If this script changes the weights of a lora layer (for example, from `<lora:example:1:ALL>` to `<lora:example:1:NONE>`), the changed value will **NOT** take any effect **because the cache** thinks that the changed lora layer is the same as the previous one, then the lora extension do **NOTHING**.
But if you changed the multiplier a little bit (for example, from `<lora:example:1:NONE>` to `<lora:example:0.99:NONE>`), the cache is dropped, then the weight changes of LoRA blocks takes effect.

### Solution
Here is a solution:
Change 262 line in `stable-diffusion-webui/extensions-builtin/lora/lora.py`:
`if current_names != wanted_names:`->`if True:`
That will disable the cache and force lora extension to reapply lora every time.

But I don't think it's a good solution, maybe we can modify this script to fix this problem.

Forgive my poor English, and feel free to ask me more about this problem.🙂

**Comment by hako-mikan** [comment]
As the side note, the cache loading is avoided by appending a random number to the LoRA name

**Comment by lwh9346** [comment]
I've tested and the problem is fixed. Thank you!
