### ISSUE TITLE
Printed Weights Bug

### ISSUE THREAD

**Issue by AI-Casanova** [hako-mikan/sd-webui-lora-block-weight#31]
`<lora:xxxx:0.5:ALL> and <lora:xxxx:1:ALL0.5>`

print the same weights to the console [0.5,0.5......]

But `0.5:ALL` actually applies at full weight, which had me chasing ghosts for ages.

**Comment by AI-Casanova** [comment]
Also, as a warning, your random number append hack does not work with batch count >1 those it does with batch size.

**Comment by hako-mikan** [comment]
The value displayed there is the strength x weight value. I have corrected the writing as it may indeed be misleading.

Thanks for reporting the batch size issue as well. This has been changed to reload on a batch-by-batch basis.
