### ISSUE TITLE
Only the strength of the last Lora in the prompt counts (and it also applies to all the other Lora in the promp)

### ISSUE THREAD

**Issue by SidAbhi** [hako-mikan/sd-webui-lora-block-weight#33]
I was confused why my  images are coming out different than from previous versions, but I finally figured out that the strength of the last lora applies to ALL the other loras.

For example if the loras are 
`<lora:exampleX:1:INALL>, <lora:exampleY:0.5:OUTS>, <lora:exampleZ:0.8:MIDD>`
Every lora will have the strength of the lora:exampleZ i,e, the above prompt is the same as
`<lora:exampleX:0.8:INALL>, <lora:exampleY:0.8:OUTS>, <lora:exampleZ:0.8:MIDD>`

It doesn't matter what loras I use, the last one will always dictate the strength of the others
`<lora:exampleZ:1:INALL>, <lora:exampleY:0.5:OUTS>, <lora:exampleX:2:MIDD>`
will produce the same result as 
`<lora:exampleZ:2:INALL>, <lora:exampleY:2:OUTS>, <lora:exampleX:2:MIDD>`

**Comment by hako-mikan** [comment]
This bug have been fixed at latest update.
