### ISSUE TITLE
ComfyUI requires lora-block-weight

### ISSUE THREAD

**Issue by xueqing0622** [hako-mikan/sd-webui-lora-block-weight#35]
Hello, lora-block-weight is a good extension, Recently, due to work reasons, we have to transfer the workflow from auto111 to comfyUI. However, lora-block-weight is essential. If the author or some code master has time, PLS create a lora-block-weight node for comfyUI,

Thank you. I wish you have a nice day!

**Comment by za-wa-n-go** [comment]
https://github.com/comfyanonymous/ComfyUI/pull/303
