### ISSUE TITLE
The first time it works normally, the second time it will enhance the effect of Lora, and after the third time it becomes completely chaotic. It returns to normal after restarting.

### ISSUE THREAD

**Issue by lfuu** [hako-mikan/sd-webui-lora-block-weight#37]
Hello, I have been experiencing this bug while using it. Only the first use is normal, especially when loading two or more Lora devices, or when adding weights like 1,0,0,0,1,1,1,1,1 , 1 , 1 , 1 , 0 , 0 , 0 , 0 , 0. The subsequent generations are all chaotic.

**Comment by AI-Casanova** [comment]
This is caused by the LoRA not being unloaded between generations. 

Are you on the latest version? That one fixed it for me.

**Comment by lfuu** [comment]
是的，我用的就是最新版9bd7fa1...，只有最新版有这个问题，我只能退到4月1日的版本d5b24cf才能使用，但4月1日的版本有时会失效几个写在后面的lora

**Comment by lfuu** [comment]
Yes, I am using the latest version 9bd7fa1... and only the latest version has this problem. I have to revert back to the April 1st version d5b24cf in order to use it, but sometimes that version will fail with a few loras written at the end.

**Comment by lfuu** [comment]
The first time it works normally, the second time it will enhance the effect of Lora, and after the third time it becomes completely chaotic. It returns to normal after restarting.
