### ISSUE TITLE
ValueError: 'IN00' is not in list

### ISSUE THREAD

**Issue by Intorain** [hako-mikan/sd-webui-lora-block-weight#39]
X:Block ID, BASE,Y: values,0, Z:none,, base:0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 (1/130)
locon load lora method
LoRA Block weight: Ralph_222-000007: 0.7 x [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
locon load lora method

Error completing request
Arguments: ('task(1kwi8o2hu3jdb9b)', '222, 1girl, solo,realistic, black hair, black eyes, looking at viewer, white background, simple background, middle hair, portrait, smile, lips, freckles, makeup,<lora:Ralph_222-000007:0.7:XYZ>, ', 'EasyNegative, paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), skin spots, acnes, skin blemishes, age spot, glans,extra fingers,fewer fingers,((watermark:2)),(white letters:1), (multi nipples), lowres, bad anatomy, bad hands, text, error, missing fingers,extra digit, fewer digits, cropped, worst quality, low qualitynormal quality, jpeg artifacts, signature, watermark, username,bad feet, {Multiple people},lowres,bad anatomy,bad hands, text, error, missing fingers,extra digit, fewer digits, cropped, worstquality, low quality, normal quality,jpegartifacts,signature, watermark, blurry,bad feet,cropped,poorly drawn hands,poorly drawn face,mutation,deformed,worst quality,low quality,normal quality,jpeg artifacts,signature,extra fingers,fewer digits,extra limbs,extra arms,extra legs,malformed limbs,fused fingers,too many fingers,long neck,cross-eyed,mutated hands,polar lowres,bad body,bad proportions,gross proportions,text,error,missing fingers,missing arms,missing legs,extra digit,', [], 30, 0, False, False, 1, 1, 7, 1531129687.0, -1.0, 0, 0, 0, False, 768, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, 'MultiDiffusion', False, 10, 10, 1, 64, False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, False, True, True, 0, 2048, 128, False, '', 0, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.external_code.ControlNetUnit object at 0x00000205B72FD4B0>, <scripts.external_code.ControlNetUnit object at 0x00000205B72FFF10>, <scripts.external_code.ControlNetUnit object at 0x00000205B72FFCD0>, False, '', 0.5, True, False, '', 'Lerp', False, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Pooling Max', False, 'Lerp', '', '', False, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5\nFace_Strong:1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0\nFace_weak:1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0.2,0,0,0,0,0\nMan1:1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0\nMan2:1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1\nStyle1:1,1,1,1,1,1,1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,0,0\nStyle2:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.8,1,1,1,1,1\nStyle3:1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1\nStyle4:1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1', True, 1, 'Block ID', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 'values', '0,0.25,0.5,0.75,1', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False, False, 3, 0, False, False, 0, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 7, 'ALL,INS,IND,INALL,MIDD,OUTD,OUTS,OUTALL', 0, '', 0, '', True, False, False, False, 0, 'Blur First V1', 0.25, 10, 10, 10, 10, 1, False, '', '', 0.5, 1, False, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "J:\AI\novelai-webui\novelai-webui-aki-v3\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "J:\AI\novelai-webui\novelai-webui-aki-v3\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "J:\AI\novelai-webui\novelai-webui-aki-v3\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "J:\AI\novelai-webui\novelai-webui-aki-v3\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 595, in newrun
    processed = script.run(p, *script_args)
  File "J:\AI\novelai-webui\novelai-webui-aki-v3\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 402, in run
    if "values" in ytype:c_base = weightsdealer(y,x,base)
  File "J:\AI\novelai-webui\novelai-webui-aki-v3\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 364, in weightsdealer
    flagger[blockid.index(id)] =changer
ValueError: 'IN00' is not in list

**Comment by hako-mikan** [comment]
Please let me know if it works with the latest version.

**Comment by AsadaKintoki** [comment]
Hi, Seems we still have the same issue but with different exceptions. I pulled the newest change and below were the error log
scripts\lora_block_weight.py", line 370, in weightsdealer
    if  blockid.index(it[1]) > blockid.index(it[0]):
ValueError: 'IN00' is not in list

it looks like not currently identify the weights_t from base, it using 17 for loyc instead of 26

The prompt I testing: <lyco:XXXX:1:1:0:XYZ>

**Comment by hako-mikan** [comment]
Ok. I found cause.
If there is `XYZ:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1` in your preset.
change to `XYZ:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1`

**Comment by AsadaKintoki** [comment]
> Ok. I found cause. If there is `XYZ:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1` in your preset. change to `XYZ:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1`

Thanks for the quick replay.
Interesting I didn't have XYZ set as preset however after put this into preset with 26 blocks it did work for lyco.
Just wondering would this has side effect for lora type XYZ?

**Comment by hako-mikan** [comment]
If you did not input preset of XYZ, it was interpreted as 17 blocks.
No problem, in case of lora with 26 blocks, it works correctly.
