### ISSUE TITLE
Enhancement: specify the weight of all 17 blocks directly in the prompt

### ISSUE THREAD

**Issue by ruSauron** [hako-mikan/sd-webui-lora-block-weight#4]
The final result I ask for:
`<lora:loraname:1:1,1,1,1,1,1,1,1,0.5,1,1,1,0.5,1,1,1,1>`
This should generate a picture with weights of 0.5 at OUT4 and OUT8 blocks, all other blocks are 1.

long read:
After using XYZ I find that I want to reduce the OUT4 and OUT8 blocks to 0.5

None of the standard tags work for me, so I need to create a new tag, such as `CREATIVENAME:1,1,1,1,1,1,1,1,1,0.5,1,1,0.5,1,1,1,1,1`

The query string will be
`<lora:loraname:1:CREATIVENAME>`

The problem is that the CREATIVENAME value may not be saved or may be accidentally changed the next day.

You can give more meaningful names to tags, for example:
`NOUT04to05OUT08to05:1,1,1,1,1,1,1,1,0.5,1,1,1,0.5,1,1,1,1`

This solves the comprehension problem, but you can still accidentally mess up or erase saved weights.

Then You can make the tag name and its values almost identical, for example:
`1_1_1_1_1_1_1_1_0.5_1_1_1_0.5_1_1_1_1:1,1,1,1,1,1,1,1,0.5,1,1,1,0.5,1,1,1,1`

The prompt will then say:
`<lora:loraname:1:1_1_1_1_1_1_1_1_0.5_1_1_1_0.5_1_1_1_1>`

And it will work, will be stored in the EXIF of the finished image. After all, the most important part of the whole issue - the lack of repeatability due to insufficient information in the EXIF 

But there is still the inconvenience of having to replace _ with , and vice versa. Why not instead add the ability to specify weights directly in the prompt?

Thank you so much for the wonderful expansion, it opens up amazing possibilities!

**Comment by hako-mikan** [comment]
Is the problem with presets not saving properly related to issue #2?
If so, I've already solved it.
Anyway, I have added the features you describe. 
Please give it a try.
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/2

**Comment by ruSauron** [comment]
Works perfect! Thank you!

> Is the problem with presets not saving properly related to issue
No, I didn't like that the prompt itself couldn't be made on another device before
