### ISSUE TITLE
Is it possible to support a1111-sd-webui-lycoris?

### ISSUE THREAD

**Issue by poko3347** [hako-mikan/sd-webui-lora-block-weight#42]
https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

**Comment by iconnoci** [comment]
The same question +1

**Comment by poko3347** [comment]
Preset for lycoris, but it doesn't work on lyco: with an error (it works on lora:).

unet_multipliers = float(params[1]) if len(params) > 1 else te_multipliers
ValueError: could not convert string to float: 'OUTD2'

**Comment by hako-mikan** [comment]
Syntax is different, use `<lyco:"lora name":1:1::OUTD2>  `

**Comment by poko3347** [comment]
Thanks, it worked correctly!
