### ISSUE TITLE
17 lora block explanation

### ISSUE THREAD

**Issue by MalfreCryvertia** [hako-mikan/sd-webui-lora-block-weight#43]
sorrt in advance as i see no discussion here, so im posting it on issue.

i still cant understand what do these weights mean
so a lora has 17 blocks in it. o..kay?
these 17 blocks, what do they exactly specify? 
is it an image divided by 17 area based on its dimension, e.g. 512x512, will be divided into 1 block for all 512x512, and 16 blocks as tiles?
![image](https://user-images.githubusercontent.com/93036999/231435479-59a7bdcc-08f3-47c5-aebc-94056e9314b8.png)
or maybe like this
![image](https://user-images.githubusercontent.com/93036999/231435661-3c843825-d5b9-4759-9498-577799a05e47.png)
or they are not based on dimensions but specification of rgb hue value saturation etc?

seeing the example having many in123 mid123 out1234 only confuses me even more

also what will happen if i turn off / uncheck the blockweight and leave the block weight then generate image?
![image](https://user-images.githubusercontent.com/93036999/231437861-7f6ec238-a5ca-454d-9041-c6a410bdf1ee.png)
![image](https://user-images.githubusercontent.com/93036999/231438340-6486a527-fe3d-4941-bc97-8963399ef858.png)
![image](https://user-images.githubusercontent.com/93036999/231438896-f35e7b71-73ee-4db5-966b-c2d33840bff9.png)

if all of my hypothesis/inferences are wrong
what do these: all, not, base, in123, mid1234, out12345 mean?

**Comment by ClashSAN** [comment]
It is not related to tiles. The architecture of the unet of models is made of blocks. It is some hidden thing.

Some theories people proposed through experimentation:
![image](https://user-images.githubusercontent.com/98228077/231521890-e6a52c6b-7b8d-465e-a4b4-0573d2c56219.png)

LoRAs has had less experimentation being done and the number of blocks to choose from is less.

`all, not, base, in123, mid1234, out12345` these are made-up names they are presets for adjusting the block weight sliders eg: "all" should mean all sliders are 100%

this is for what you described first. https://github.com/hako-mikan/sd-webui-regional-prompter

**Comment by iconnoci** [comment]
@ClashSAN     what is stable diffusion 1.x based clip?

**Comment by hako-mikan** [comment]
https://rentry.org/BlockMergeExplained

**Comment by Wambosa** [comment]
Thank everyone here for the question and discussion! 
I feel a much better grasp on how this stuff works 🤓
