### ISSUE TITLE
The plugin suddenly crushed today

### ISSUE THREAD

**Issue by gdx09090909** [hako-mikan/sd-webui-lora-block-weight#44]
These tags suddenly cannot be read, and scripts report an error
![屏幕截图 2023-04-14 153808](https://user-images.githubusercontent.com/119488914/231977448-a51fa63d-21ca-49fa-b850-d0632257fdd3.jpg)
After tossing and turning for a while, I replaced Lohcon with Lycoris, which resulted in more serious errors
![屏幕截图 2023-04-14 153844](https://user-images.githubusercontent.com/119488914/231977719-cbe7a5c5-5f8e-4075-af83-f09962d548fb.jpg)

**Comment by gdx09090909** [comment]
![屏幕截图 2023-04-14 154947](https://user-images.githubusercontent.com/119488914/231979858-45b975fd-e470-4c05-ba6e-dbda26106f5e.jpg)
that's when i use <lora:1.5mix:0.4:1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1>instead of <lora:1.5mix:0.4:OUTALL>

**Comment by hako-mikan** [comment]
Old version is not support a1111-sd-webui-lycoris.
Use latest version.
