### ISSUE TITLE
how to block weight ia3 AND  LOKR ?

### ISSUE THREAD

**Issue by gdx09090909** [hako-mikan/sd-webui-lora-block-weight#47]
a lokr lycoris, i use <lyco:1.5lokrrryu:0.8:0.8> or <lyco:1.5lokrrryu:0.8:0.8:LOHA1> 
LOHA1:1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1
![03405-288712913-absurdres,incredibly absurdres,masterpiece,best quality,high quality highres _1boy,solo,manly,male focus,  anime style,watercolo](https://user-images.githubusercontent.com/119488914/232651000-b95c6aab-b059-4877-8dbb-24cd76de5a51.png)
![03406-288712913-absurdres,incredibly absurdres,masterpiece,best quality,high quality highres _1boy,solo,manly,male focus,  anime style,watercolo](https://user-images.githubusercontent.com/119488914/232651005-babea3c6-6419-4718-b0f8-415f3e4599c1.png)

I dont know,the diffrence is small compared to lora  block weight.

<lyco:1.5lokrrryu:0.8:0.8:0:LOHA1>  will show 
    lbw(lycomo.loaded_lycos[l],lwei[n],elements[n])
IndexError: list index out of range
i don't use dylora,

**Comment by hako-mikan** [comment]
Are you using latest version?
I fixed similar error yesterday.
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/46

**Comment by gdx09090909** [comment]
> Are you using latest version? I fixed similar error yesterday. #46

OH!it works now!  the images are quite different,I have a question, is the layering of IA3 and lokr both 26 layers? I found that their OUT layer performance is significantly different from Lora's "OUTALL",

**Comment by hako-mikan** [comment]
Maybe 26, but it is easy to check and you can use the Effective Block checker to determine which block is valid.
