### ISSUE TITLE
I am calling the api interface of webui, how should I add your function in the script

### ISSUE THREAD

**Issue by xxtyy** [hako-mikan/sd-webui-lora-block-weight#50]
I am calling the api interface of webui, how should I add your function in the script.

import requests
import cv2
from base64 import b64encode

def readImage(path):
    img = cv2.imread(path)
    retval, buffer = cv2.imencode('.jpg', img)
    b64img = b64encode(buffer).decode("utf-8")
    return b64img

b64img = readImage(r"C:\Users\Administrator\Desktop\test\demo1.jpg")
class controlnetRequest():
    def __init__(self, prompt):
        self.url = "http://localhost:7860/sdapi/v1/txt2img"
        self.body = {
            "prompt": "<lora:akemiTakada1980sStyle_1:0.75:OUTALL>,takada akemi, 1980s \(style\),painting \(medium\), retro artstylewatercolor,looking at viewer,solo,upbody,zz00,eyes_zz00,hair_zz00,\(medium\)1girl,woman,famale,skyzz00,<lora:zz00:0.6:MIDD>,portrait_zz00,lips_zz00,",
            "negative_prompt": "(painting by bad-artist-anime:0.9), (painting by bad-artist:0.9), watermark, text, error, blurry, jpeg artifacts, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, artist name, (worst quality, low quality:1.7), bad anatomy,",
            "seed": -1,
            "subseed": -1,
            "subseed_strength": 0,
            "batch_size": 1,
            "n_iter": 1,
            "steps": 20,
            "cfg_scale": 7,
            "width": 512,
            "height": 512,
            "restore_faces": True,
            "eta": 0,
            "sampler_index": "DPM++ 2M Karras",
            "alwayson_scripts": {
                "LoRA Block Weight":{
                    "Active": True,
                },
                "ControlNet": {
                    "args": [
                    {
                        "enabled": False,
                        "input_image": [b64img],
                        "module": 'softedge_hed',
                        "model": 'control_v11p_sd15_softedge [a8575a2a]'
                    },
                    {
                        "enabled": False,
                        "input_image": "",
                        "module": "",
                        "model": ""
                    }
                    ]
                }
            }
        }

    def sendRequest(self):
        r = requests.post(self.url, json=self.body)
        response = r.json()
        print(response)
        return response

js = controlnetRequest("walter white").sendRequest()
print(js)

import io, base64
from PIL import Image

#pil_img = Image.open(r"C:\Users\Administrator\Desktop\test\demo1.jpg")
image1 = Image.open(io.BytesIO(base64.b64decode(js["images"][0])))
#image2 = Image.open(io.BytesIO(base64.b64decode(js["images"][1])))
print(image1)
#print(image2)
# 将 Pillow 图像对象保存为 JPEG 文件
image1.save(r"C:\Users\Administrator\Desktop\test\test1.jpg", format='JPEG')
#image2.save(r"C:\Users\Administrator\Desktop\test\test2.jpg", format='JPEG')
image1.show()
#image2.show()

This code will report an error:
Error running process: D:\novelai-webui-aki-v3\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "D:\novelai-webui-aki-v3\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\novelai-webui-aki-v3\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 208, in process
    loraratios=loraratios.splitlines()
AttributeError: 'dict' object has no attribute 'splitlines'

**Comment by hako-mikan** [comment]
Looking your error, it seems that you use old version of this script. 
Try latest version.

**Comment by xxtyy** [comment]
Yes, you are right.
I tested on API and worked too.

**Comment by xxtyy** [comment]
Why do I have an error when I use the api
Error running process: D:\novelai-webui-aki-v3\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "D:\novelai-webui-aki-v3\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\novelai-webui-aki-v3\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 208, in process
    loraratios=loraratios.splitlines()
AttributeError: 'dict' object has no attribute 'splitlines'

**Comment by xxtyy** [comment]
> 查看您的错误，您似乎使用了此脚本的旧版本。 请尝试最新版本。 我在 API 上进行了测试并成功了。

I switched to a new version and still can't use it

**Comment by xxtyy** [comment]
I think the passed json format is dict, and the passed parameters you set are in the form of strings

**Comment by hako-mikan** [comment]
`loraratios=loraratios.splitlines()` on line 208 is an old file such as version 4. 
https://github.com/hako-mikan/sd-webui-lora-block-weight/blob/ver4/scripts/lora_block_weight.py

Delete the file and reinstall the latest version.
