### ISSUE TITLE
 The default value of DyLoRA in LyCORIS should be of type None, rather than [0]

### ISSUE THREAD

**Issue by avan06** [hako-mikan/sd-webui-lora-block-weight#51]
Hi,

Regarding the README instructions for using LyCORIS from a1111-sd-webui-lycoris, the recommendation to set DyLoRA to [ :0: ] may not be correct. 
> README.md
For LyCORIS using a1111-sd-webui-lycoris, syntax is different. :1:1:0:IN02you need to input two value for textencoder and U-net, and :0: for DyLoRA. a1111-sd-webui-lycoris is under under development, so this syntax might be changed.

This is because the initial value of DyLoRA in LyCORIS is of type None, and setting it to a value (e.g. 0) may result in different behavior compared to the default value.

In lycoris.py code, the default value of dyn_dims is None, as specified in line 471.
> a1111-sd-webui-lycoris/lycoris.py
...
def load_lycos(names, te_multipliers=None, unet_multipliers=None, dyn_dims=None):
...
lyco.dyn_dim = dyn_dims[i] if dyn_dims else None

Can you please confirm? Thank you!

**Comment by hako-mikan** [comment]
Thanks. You are correct.
I Confirmed and rewritten README.
