### ISSUE TITLE
You really do a good job,and I just have a little question:)

### ISSUE THREAD

**Issue by evergreenqingyu** [hako-mikan/sd-webui-lora-block-weight#52]
I'm really poor in code,so could you please tell me how to set this extension to not start automatically,thanks!

**Comment by hako-mikan** [comment]
It's easy.
Find `ui-config.json` in web-ui directory and open.
Find `"customscript/lora_block_weight.py/txt2img/Active/value": true,"` and change `true` to `false`

**Comment by evergreenqingyu** [comment]
thanks!
