### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by 4KsTan** [hako-mikan/sd-webui-lora-block-weight#56]
activating extra network lyco with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001C090D221D0>]: ValueError
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\AI\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\extra_networks_lyco.py", line 69, in activate
    te, unet, dyn_dim = parse_args(params.items[1:])
  File "C:\AI\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\extra_networks_lyco.py", line 35, in parse_args
    x = type(x)
ValueError: invalid literal for int() with base 10: 'LyALL
'

**Comment by 4KsTan** [comment]
someone can help me?  when <lyco:onimai-cs1-dim8-4-loha-step-30000:1:1::ALL>

**Comment by 4KsTan** [comment]
> `::` make error. use `:=:` `<lyco:"lora name":1:1:=:LyALL>`

same problem

**Comment by hako-mikan** [comment]
It appears that LyCORIS has changed its processing method. 
Use `<lyco:"lora name":1:lbw=LyALL>` etc. after updating.

**Comment by 4KsTan** [comment]
Apply LyCORIS model: "lora name"
Text encoder weight: 1.0
Unet weight: 1.0
DyLoRA Dim: None
========================================
100% -------------------------------------------------------------
Total progress 100% ---------------------------------------------


i have tried below syntax seems like no any effect or its normal only for Lyco without showing-
example like (lora):
 (LoRA Block weight (lora): beautifulDetailedEyes_v10: 0.6 x [1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0])
<lyco:"lora name"1:1:1bw=LyALL>
<lyco:"lora name"1:1bw=LyALL>

**Comment by 4KsTan** [comment]
> It appears that LyCORIS has changed its processing method. Use `<lyco:"lora name":1:lbw=LyALL>` etc. after updating.

Apply LyCORIS model: "lora name"
Text encoder weight: 1.0
Unet weight: 1.0
DyLoRA Dim: None
========================================
100% -------------------------------------------------------------
Total progress 100% ---------------------------------------------


i have tried below syntax seems like no any effect or its normal only for Lyco without showing-
example like (lora):
 (LoRA Block weight (lora): beautifulDetailedEyes_v10: 0.6 x [1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0])
<lyco:"lora name"1:1:1bw=LyALL>
<lyco:"lora name"1:1bw=LyALL>

**Comment by 4KsTan** [comment]
thank you.
