### ISSUE TITLE
Can you provide an example of XYZ plot?

### ISSUE THREAD

**Issue by xiaoyoucheng** [hako-mikan/sd-webui-lora-block-weight#6]
Can you provide an example of  XYZ plot? 
I have been testing it for a while and still don't know how to use it.

![image](https://user-images.githubusercontent.com/33143581/222877673-544ed701-bab9-4faf-bb19-ae2ddaa3272a.png)

**Comment by hako-mikan** [comment]
The image you showed should work.
If it doesn't work, check your settings. 
It should be assumed \<lora: "loraname":1:XYZ>.
Another example is written in README.

**Comment by xiaoyoucheng** [comment]
> The image you showed should work. If it doesn't work, check your settings. It should be assumed <lora: "loraname":1:XYZ>. Another example is written in README.

I previously attempted to use <lora: "loraname":1:xyz>, but encountered issues. I have since tried using <lora: "loraname":1:XYZ> and it is now functioning properly. Thank you for your assistance.

**Comment by xiaoyoucheng** [comment]
There is a distinction between capitalized and non-capitalized words.

**Comment by hako-mikan** [comment]
Yes.  I added that in README. Thank you.
