### ISSUE TITLE
when I use api, I get an error

### ISSUE THREAD

**Issue by ym-ctw** [hako-mikan/sd-webui-lora-block-weight#60]
Error running process: /home/ec2-user/SageMaker/stable-diffusion-webui/extensions/sd-webui-lora-block-weight/scripts/lora_block_weight.py
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/home/ec2-user/SageMaker/stable-diffusion-webui/extensions/sd-webui-lora-block-weight/scripts/lora_block_weight.py", line 254, in process
    elemental = elemental.split("\n\n")
AttributeError: 'NoneType' object has no attribute 'split'

My prompt is: 
a cup of juice, (white background :1.2),  <lora:ystyle2-Lyriel-000002:1:0.8,0,1,0.8,0,1,1,0,1,0.5,0,0,0,1,0,0,0,0.5,0.8,0.3,0.2,0.2,0.3,0,0.3,0.3>

**Comment by hako-mikan** [comment]
I have fixed to prevent the error from occurring, but I don't know if I can use it because I don't know what causes that error to occur. Are you using a special web-ui version?

**Comment by ym-ctw** [comment]
> I have fixed to prevent the error from occurring, but I don't know if I can use it because I don't know what causes that error to occur. Are you using a special web-ui version?

My webui version is committ: 9377092a892687a8ae43ba5f7df44f0929ab2997. This error didn't occur when I use the same prompt in webui's txt2img textbox without api. But when I use api and input the same type prompt, It give me this error.

Did my webui version cause this?

**Comment by ym-ctw** [comment]
> I have fixed to prevent the error from occurring, but I don't know if I can use it because I don't know what causes that error to occur. Are you using a special web-ui version?

I update the latest lora-block extension version,  now no error but it seems that it didn't use lora block in api.
This is my curl and param, is there anything  I missed in param?

    curl -X 'POST' \
      'http://127.0.0.1:7860/sdapi/v1/txt2img' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '{
      "enable_hr": false,
      "denoising_strength": 0,
      "firstphase_width": 0,
      "firstphase_height": 0,
      "hr_scale": 2,
      "hr_upscaler": "string",
      "hr_second_pass_steps": 0,
      "hr_resize_x": 0,
      "hr_resize_y": 0,
      "prompt": "ystyle, a cup of juice, (white background :1.2), <lora:ystyle2-Lyriel-000002:1:0.8,0,1,0.8,0,1,1,0,1,0.5,0,0,0,1,0,0,0,0.5,0.8,0.3,0.2,0.2,0.3,0,0.3,0.3>",
      "styles": [
        "string"
      ],
      "seed": 999,
      "subseed": -1,
      "subseed_strength": 0,
      "seed_resize_from_h": -1,
      "seed_resize_from_w": -1,
      "sampler_name": "DPM++ 2M Karras",
      "batch_size": 1,
      "n_iter": 1,
      "steps": 25,
      "cfg_scale": 7,
      "width": 512,
      "height": 512,
      "restore_faces": false,
      "tiling": false,
      "do_not_save_samples": false,
      "do_not_save_grid": false,
      "negative_prompt": "EasyNegative,  (bad_prompt_version2:0.8), (worst quality, low quality:1.4), text, signature, watermark, username, ((out of frame)), 1girl, blurry, shadow, ((reflection ))",
      "eta": 0,
      "s_churn": 0,
      "s_tmax": 0,
      "s_tmin": 0,
      "s_noise": 1,
      "override_settings": {},
      "override_settings_restore_afterwards": true,
      "script_args": [],
      "send_images": true,
      "save_images": false,
      "alwayson_scripts": {}
    }'

**Comment by ym-ctw** [comment]
It seems that the latest webui don't have this error . I closed this issue!
