### ISSUE TITLE
I got two errors

### ISSUE THREAD

**Issue by blackteeth1990** [hako-mikan/sd-webui-lora-block-weight#62]
**I got two errors.**
Error running process: E:\sd-webui-aki-v4.1\extensions\sd-webui-LoRA-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4.1\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "E:\sd-webui-aki-v4.1\extensions\sd-webui-LoRA-block-weight\scripts\lora_block_weight.py", line 263, in process
    elementals[e0.strip()]=e.split(":",1)[1]
IndexError: list index out of range
Error running process_batch: E:\sd-webui-aki-v4.1\extensions\sd-webui-LoRA-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4.1\modules\scripts.py", line 436, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "E:\sd-webui-aki-v4.1\extensions\sd-webui-LoRA-block-weight\scripts\lora_block_weight.py", line 290, in process_batch
    loradealer(o_prompts ,self.lratios,self.elementals)
AttributeError: 'Script' object has no attribute 'lratios'
**this is my prompt:**masterpiece, best quality, masterpiece,official art,detailed,
<lyco:Style_GlassyandGlaze (FATA)_v1.0:1:1:lbw=1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0>,
Brilliant light and shadow,Back lit,1girl, side blunt bangs,hairs between eyes,Red eyes,delicate face, ribbons,White Dress, bowties, buttons, bare shoulders,Detached Sleeve,(small breast), ((breeze)), Flying splashes,wind,Long flowing hair,(Broken glass),Grey hair,The flying water,Hair covering your body,The flying red ribbon,ocean in background,
nahida_genshin,cross-shaped,pupils,default_dress,green cape,
 <lora:Nahida:1>
my web ui runs fine when disable this extension

**Comment by hako-mikan** [comment]
Tell me your web-ui version.

**Comment by blue98060247** [comment]
I have the same issue. When using the extension, I'm getting an 'AttributeError: 'Script' object has no attribute 'lratios'' error. Here are the versions of my web UI components:
python: 3.10.6
torch: 1.13.1+cu117
xformers: 0.0.17.dev476
gradio: 3.16.2
commit: a9fed7c3
checkpoint: 7f96a1a9ca
I'm using the sd-webui-lora-block-weight version 574493d8. 
Let me know if you need any additional information.

**Comment by hako-mikan** [comment]
It is a difficult problem. 
I think it can probably be solved by updating the version of the web-ui. 
Is that difficult?
