### ISSUE TITLE
LoRA Block Weight not applying during Hires. fix after A1111 webui v1.3.0 update

### ISSUE THREAD

**Issue by aninsultedcat** [hako-mikan/sd-webui-lora-block-weight#67]
### After updating A1111 webui to v1.3.0, the LoRA Block Weight extension no longer applies during Hires. fix steps.

A1111 webui will apply and respect the \<lora:alias:strength:weights\> during the initial generative steps, but will ignore the :weights part during Hires. fix steps, treating \<lora:alias:strength:weights\> as \<lora:alias:strength\>. This can be confirmed by enabling "Hires fix: show hires prompt and negative prompt (requires restart)" in the Settings under User interface and manually prompting a LoRA with :weights in the hires prompt box. The generated output will always be the same, no matter what :weights are used.

The extension loses value when it is ignored for Hires. fix steps, as it defeats the extension's purpose when Hires. fix is a part of the workflow. 

**Current workaround:** Generate images without Hires. fix enabled, sending a generated txt2img ouput to img2img, having enabled "With img2img, do exactly the amount of steps the slider specifies. (normally you'd do less with less denoising)" in the Settings under Stable Diffusion, and scaling the image with the same prompts, Sampler, Steps, Resize by Scale, CFG, Denoising strength and Seed as you would have used during Hires. fix, additionally having put upscaler_for_img2img in the Quicksettings list (Settings, User interface) to also select the Upscaler you would have used during Hires. fix, then generating the upscaled image. This produces an almost identical output to v1.2.1 images as the img2img process will respect the extension's :weights.

**Visual representation of the issue (txt2img w/ Hires. fix enabled in v1.2.1 and v1.3.0):**

![LoRA_Block_Weights__Hires-fix_issue](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/135176973/5a03ee55-a102-44ab-a843-4fcccf0bcaa9)

**Comment by aninsultedcat** [comment]
Issue still persists in the current 1.4.0-RC build.

**Comment by martin-rizzo** [comment]
Since version v1.3.0, A1111 webui supports the ability to use two different prompts. One prompt is for normal image generation, and the other prompt is for the 'Hires fix' step. This change resulted in significant modifications to the txt2img code, primarily in the `process_images_inner(p: StableDiffusionProcessing)` function of the **processing.py** script.

I have been reviewing the code of the latest tag 'v1.4.0-RC' and noticed this:

1) The code used for image generation does the following:
**Line 713: stable-diffusion-webui/modules/processing.py**
```python

   # Here, the 'activate(..)' function is called, which internally
   # calls 'lora.load_loras(names, multipliers)' to load the configuration
   # of all used loras (but only with the main weight)
   if not p.disable_extra_networks:
       with devices.autocast():
           extra_networks.activate(p, p.extra_network_data)

   # Here, the 'process_batch(..)' function of the extensions is called,
   # where 'LoRA Block Weight' adjusts the block-by-block weight of each lora
   if p.scripts is not None:
       p.scripts.process_batch(p, batch_number=n, prompts=p.prompts, seeds=p.seeds, subseeds=p.subseeds)
```
2) The code used during the 'Hires fix' does the following:
**Line 1068: stable-diffusion-webui/modules/processing.py**
```python

   # Here, the 'activate(..)' function is called again, which again calls
   # 'lora.load_loras(names, multipliers)' and reloads the configuration
   # of all used loras (but only with the main weight!!)
   if not self.disable_extra_networks:
       with devices.autocast():
           extra_networks.activate(self, self.hr_extra_network_data)

   # The problem is that A1111 does not call any extension function here(!).
   # Therefore, 'LoRA Block Weight' doesn't have a chance to adjust
   # the block-by-block weight again.
```

I hope this information is helpful in resolving the bug. Regards!

**Comment by martin-rizzo** [comment]
A possible temporary fix/hack could be to disable the 'extra networks' during the hires.fix step, so that the configuration of LoRAs is not reloaded. This could be done in the extension's code as follows:

**Line 288: sd-webui-lora-block-weight/scripts/lora_block_weight.py**
```python
  def process_batch(self, p, loraratios,useblocks,xyzsetting,xtype,xmen,ytype,ymen,ztype,zmen,exmen,eymen,ecount,diffcol,thresh,revxy,elemental,elemsets,**kwargs):
        if useblocks:
	    # Fix/hack to prevent the LORAs configuration from being reset
            # during the 'hires.fix' step. I'm not sure about the potential
            # consequences for the rest of the options.
            p.disable_extra_networks = True
            o_prompts = [p.prompt]
            for prompt in prompts:
                if "<lora" in prompt or "<lyco" in prompt:
                    o_prompts = prompts.copy()
            loradealer(o_prompts ,self.lratios,self.elementals)

```
I hope this helps!
