### ISSUE TITLE
XYZ plot can't generate grid image

### ISSUE THREAD

**Issue by mamgam** [hako-mikan/sd-webui-lora-block-weight#71]
i used webui with colab 
i tested original weight but it dosen't make gird image
![aaaa](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/127020082/1f6cf33f-a627-45f5-ac46-7880eed6f209)
![aa](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/127020082/1f959e66-6421-4b09-9b8c-b31e45caa076)
![aaa](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/127020082/45cacdf7-ea73-4f53-9089-414a8bf2727e)

used web ui version is 
version: [v1.3.2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/baf6946e06249c5af9851c60171692c44ef633e0)  •  python: 3.10.12  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.32.0  •  checkpoint: [56804eb68d]
please help me

**Comment by hako-mikan** [comment]
Did you modify the script?
Your error message, is `return XYZ.truetype(fontpath, fontsize)` 
Correct code is `return ImageFont.truetype(fontpath, fontsize)`
How about reinstall this script.
