### ISSUE TITLE
What does the text box near Active do?

### ISSUE THREAD

**Issue by XuWeinan123** [hako-mikan/sd-webui-lora-block-weight#72]
If I empty it, does it mean the Weights setting's parameters will not work?

**Comment by aninsultedcat** [comment]
The Active's text box shows the aliases from the lbwpresets.txt weights that are loaded into the "Weights setting" text box. If you delete the text in Active's text box manually, the extension will still function and grab the weights from the aforementioned "Weights setting" text box. If you delete the weights from the "Weights setting" text box however, the extension does not know what the alias weights are anymore and default to weights of 1. Active's text box is a visual representation, probably meant for quick and easy copy-pasting when performing an XYZ plot using Original Weights. The text box could honestly be made to have the HTML attribute readonly="readonly", still allowing for copy-pasting.
