### ISSUE TITLE
lycoris models take no effect when both lora and lycoris model used

### ISSUE THREAD

**Issue by SwingCosmic** [hako-mikan/sd-webui-lora-block-weight#73]
Use  `a1111-sd-webui-lycoris` plugin and latest `sd-webui-lora-block-weight`. 
If both two type models used in prompts, only **LoRA** models take effect.
But console logs the block weights of the **LyCORIS models**, not LoRA's?????
我TM直接~~疑惑~~未解之谜

**Comment by hako-mikan** [comment]
It should be possible to use them even when they coexist.
Are you using a different syntax for lycos and loras?
```
<lora:"lora name":1:IN02>  
<lyco:"lora name":1:1:lbw=IN02> 
```
