### ISSUE TITLE
new after_extra_networks_activate callback

### ISSUE THREAD

**Issue by w-e-w** [hako-mikan/sd-webui-lora-block-weight#74]
better suited for your use case
see PR `add callback after_extra_networks_activate` https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11488

**Comment by hako-mikan** [comment]
Thanks! 
This will make the process much easier.

**Comment by w-e-w** [comment]
since I'm not the one using the Callback I'm not sure if the Callback is actually good or maybe it's missing something
if I'm understanding things correctly you should be able to utilize the extra network data to decide what you're going to do
if you would like anything change about that call back please voice them
preferably sooner before it makes its way into master
there I might still be a chance to change it
