### ISSUE TITLE
xyz-plot does not work on lycoris

### ISSUE THREAD

**Issue by AEye-K** [hako-mikan/sd-webui-lora-block-weight#77]
[MYpresets.txt](https://github.com/hako-mikan/sd-webui-lora-block-weight/files/12081632/MYpresets.txt)

I've added a new preset for lycoris.But when I used xyz-plot, I found that layered control didn't work for lycoris.Here's how I formatted it:
<lyco:mika_locon_v3l:1:lbw=Ly_NONE>
prompt s/r: Ly_NONE,Ly_ALL,Ly_INS,Ly_IND,Ly_INALL,Ly_MIDD,Ly_OUTD,Ly_OUTS,Ly_OUTALL

**Comment by hako-mikan** [comment]
To use XYZ plot, you must set XYZ for preset.
Try `lyco:mika_locon_v3l:1:lbw=XYZ`

**Comment by AEye-K** [comment]
I'm using xyz-plot that comes with webUI.

**Comment by hako-mikan** [comment]
I got it.
I tested it now, but it works well.
Is there any errors in command prompt?

**Comment by AEye-K** [comment]
Do you have any other social accounts, please? I'm a little uncomfortable communicating here.

**Comment by hako-mikan** [comment]
No.
`ValueError: could not convert string to float: 'Ly_OUTALL'`
this error occurs when `Ly_OUTALL` is set without `lbw=`.

**Comment by AEye-K** [comment]
Ok, I'll try it again. By the way, I see that the lycoris format has been updated recently. I wonder if this will have an effect on the lbw writing format.

**Comment by hako-mikan** [comment]
Yes.
Dose it work without XYZ plot?

**Comment by hako-mikan** [comment]
For such purposes, why not use this extension's XYZ plot or Effective Blocks Checker?

**Comment by AEye-K** [comment]
Copy that. I'll test it again. Thank you for being so patient with me.

**Comment by hako-mikan** [comment]
If you still have the problem, please let me know your environment.

**Comment by AEye-K** [comment]
Effective Block Analyzer still not working.My tag is`<lyco:扁平v12_12:1:lbw=XYZ>`.Only one picture appeared.
My version of the webUI is `68f336b`.
Do I need to provide any other information?

**Comment by hako-mikan** [comment]
What errors do I get when using XYZ?

**Comment by hako-mikan** [comment]
Similar problems have been reported, so if you still have problems, report them in the following issue.
This issue is closed to avoid confusion.
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/94
