### ISSUE TITLE
Doesn’t seem to work with webui RC 1.5.0 onwards.

### ISSUE THREAD

**Issue by sashasubbbb** [hako-mikan/sd-webui-lora-block-weight#78]
With the new implementation of ‘official’ support of multiple lora modules since RC 1.5.0 the lora block weight extension doesn’t seem to be working.

```
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x00000191EEE85F90>, <modules.extra_networks.ExtraNetworkParams object at 0x00000191EEE87130>]: ValueError
Traceback (most recent call last):
  File "B:\AIimages\stable-diffusion-webui-dev\stable-diffusion-webui\modules\extra_networks.py", line 104, in activate
    extra_network.activate(p, extra_network_args)
  File "B:\AIimages\stable-diffusion-webui-dev\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 28, in activate
    unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier
ValueError: could not convert string to float: 'style'
```

**Comment by hako-mikan** [comment]
may be fixed

**Comment by xueqing0622** [comment]
same Error: 
ValueError: could not convert string to float: 'style'
Even the num:
ValueError: could not convert string to float: '1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0

**Comment by hako-mikan** [comment]
to use in web-ui 1.5, use following syatax

<lora:"lora name":1:1:lbw=IN02>  
<lora:"lora name":1:1:lbw=1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0>

**Comment by xueqing0622** [comment]
what is ":1:1" mean,  there are 2 num about the weight?

**Comment by hako-mikan** [comment]
unet and text encoder strength
see https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

**Comment by xueqing0622** [comment]
many thx, have a nice day!
