### ISSUE TITLE
XYZ Effective Block Analyzer bug?

### ISSUE THREAD

**Issue by weisuowuyu** [hako-mikan/sd-webui-lora-block-weight#80]
The image generation process is normal, but an error is reported during the final composition: OSError: cannot open resource.
![QQ图片20230720131132](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/37931370/c3bfd16e-7309-4754-af75-d5967b092fe5)

**Comment by hako-mikan** [comment]
change directory `sd-webui-lora-block-weight-main` to `sd-webui-lora-block-weight`

**Comment by weisuowuyu** [comment]
thank you very much! I solve the questions.
