### ISSUE TITLE
2 sd-webui-lora-block-weight

### ISSUE THREAD

**Issue by xueqing0622** [hako-mikan/sd-webui-lora-block-weight#81]
after I change the "sd-webui-lora-block-weight" name in  extension  to "01sd-webui-lora-block-weight" to change the order of extensions, and the lbwpreset is missing, after I change back to "sd-webui-lora-block-weight" , the lbwpreset is back. but
there are 2 sd-webui-lora-block-weight now,
![Image text](https://i.imgur.com/EsozuJi.jpg)

**Comment by xueqing0622** [comment]
after reinstall sd webui, when i update to 1.41 still 2 2 sd-webui-lora-block-weight

**Comment by hako-mikan** [comment]
to use in web-ui 1.5, use following syatax
```
<lora:"lora name":1:1:lbw=IN02>  
<lora:"lora name":1:1:lbw=1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0>  
```

**Comment by hako-mikan** [comment]
If you are using this in API mode, its correct behavior.
Other directory names can also be used now.

**Comment by xueqing0622** [comment]
ok, turn off the api mode, the "sd-webui-lora-block-weight" is not show after script, but why other extension is not show when enable the --api

**Comment by hako-mikan** [comment]
This extension uses unusual way to enable XYZ plot in API mode.
So only this extension show when API mode is enabled.
