### ISSUE TITLE
XYZ plot is not enabled on both webui 1.41 and 1.5

### ISSUE THREAD

**Issue by JFweimo** [hako-mikan/sd-webui-lora-block-weight#83]

**Comment by hako-mikan** [comment]
Too little information. 
It works fine in my environment, so it is possible that you are using it incorrectly or there is a conflict with another extension.

**Comment by hako-mikan** [comment]
Are you using in with API option?

**Comment by hako-mikan** [comment]
Similar problems have been reported, so if you still have problems, report them in the following issue.
This issue is closed to avoid confusion.
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/94
