### ISSUE TITLE
Using "X" weights after webui 1.5.0

### ISSUE THREAD

**Issue by magpie514** [hako-mikan/sd-webui-lora-block-weight#85]
I figured out the new syntax for common usage with tags and individual weights, but I can't figure out how to alter weights marked as X in the presets with the new syntax style, even reading the code.
This functionality was very useful to troubleshoot and debug trained LoRAs, so it's sorely missed in the update.

Perhaps it could be implemented as an extra parameter similar to `lbw`? something like "xval" or "val" or even "x" (for brevity),
so it could look like `<lora:mylora:1:1:lbw=OUTX:x=0.4>`.

Thank you very much, and for writing this useful extension.

**Comment by hako-mikan** [comment]
Fixed.
Use `x=`

**Comment by magpie514** [comment]
Works perfectly, I'll close this issue since it's solved.
Thanks again!
