### ISSUE TITLE
Lora Block Weight no longer working if we enable highres-fix after SD-webui 1.5

### ISSUE THREAD

**Issue by LianmingW** [hako-mikan/sd-webui-lora-block-weight#87]
I was facing issue with this extension when I upgraded to webui 1.51. After some investigation, I figured out the extension was only not working when I enabled the highres-fix.
Prompt I used to tigger the LBW: <lyco:3DMM_V12:1:1:lbw=MIDD>,
Below is the XYZ plot I created. Both using exactly the same prompt and same seed. As you could see, we can see various result when Highres is not enabled, but when its enabled, all preset is producing same outcome.

Highres not enabled
![xyz_grid-0044-3885693546-(masterpiece_1 2), (best quality_1 2), highly detailed, extremely detailed CG unity 8k wallpaper, highres, (extremely delicate a](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/32531235/57bad14c-8ee3-4d2d-8a02-254ef660e199)

Highres enabled
![xyz_grid-0045-3885693546-(masterpiece_1 2), (best quality_1 2), highly detailed, extremely detailed CG unity 8k wallpaper, highres, (extremely delicate a](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/32531235/33657f95-d626-4c87-85b6-bb0d92cb5530)

snapshot of console output
<img width="844" alt="2023-07-27 161831" src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/32531235/19176e65-9ef8-4d3f-9315-63cd7970bd6d">

**Comment by hako-mikan** [comment]
I couldn't reproduce it.
But some fix were done so try it.

**Comment by LianmingW** [comment]
Its fixed after the code change. Thanks!
