### ISSUE TITLE
Error When Adding New Presets

### ISSUE THREAD

**Issue by Neverdusk** [hako-mikan/sd-webui-lora-block-weight#88]
For some reason, whenever I add a new preset, I get the following error: 

*** Error running process_batch: C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "C:\Users\silve\Documents\AI Art\__SDUX\modules\scripts.py", line 491, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 306, in process_batch
        loradealer(self, o_prompts ,self.lratios,self.elementals)
      File "C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 571, in loradealer
        if len(lorars) > 0: load_loras_blocks(self, lorans,lorars,multipliers,elements,ltype)
      File "C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 597, in load_loras_blocks
        lbw(lora.loaded_loras[l],lwei[n],elements[n])
    IndexError: list index out of range

---

I've been using custom LBW presets for a while now, and they still work perfectly. But adding new ones results in errors. I've even tried copying default presets under a different name, and I still receive an error. 

I'll post my preset list below. The old custom presets (NBASE-BASENINALL) work just fine. The presets I try to add (MIDD2-OUTS3) result in the error. I already press Save Presets and Reload Tags before trying to generate, so I'm not fully sure what the issue is.

NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
ALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
INS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
IND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0
INALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0
MIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0
OUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0
OUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1
OUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1
ALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5

NBASE:0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
NIN01:1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
NIN02:1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1
NIN04:1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1
NIN05:1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1
NIN07:1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
NIN08:1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1
NMID:0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1
NOUT03:1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1
NOUT04:1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
NOUT05:1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1
NOUT06:1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1
NOUT07:1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1
NOUT08:1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1
NOUT09:1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1
NOUT10:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1
NOUT11:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
NINS:0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1
NIND:1,1,1,1,0,0,0,1,1,1,1,1,1,1,1,1,1
NINALL:0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1
NMIDD:1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1
NOUTD:1,1,1,1,1,1,1,1,0,0,0,0,1,1,1,1,1
NOUTS:1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0
BASENINALL:1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1

MIDD2:1,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0
MIDD3:1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
NMIDD2:1,1,1,1,1,1,0,0,0,0,1,1,1,1,1,1,1
NMIDD3:1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1
OUTS2:0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1
OUTS3:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1

Edit: Manually writing the weights in the Lora <lora:name:1:x,x,x,x,x,x,x,x,etc> works fine. It's just calling the LBW by name <lora:name:1:MIDD2> that gives the error.

**Comment by hako-mikan** [comment]
It appears you are using an older version. 
Why don't you try updating it?

**Comment by hako-mikan** [comment]
How about writing directly to a text file?

**Comment by Neverdusk** [comment]
If I write a new preset to lbwpresets.txt while the UI is open, the same error occurs. So no matter what way I do it, adding a new preset causes errors if they're used before restarting the UI.

**Comment by Neverdusk** [comment]
That's the only related error I have. It only happens when I add a new line to the preset list. So I can only guess it has to do with some variable or list not updating until the UI / extension is restarted.

**Comment by hako-mikan** [comment]
Yeah, I changed that point.

**Comment by hako-mikan** [comment]
before errors, is there any comment such as `LoRA Block weight (lora): lora_name`?

**Comment by Neverdusk** [comment]
Yes, but it only shows for the Loras not using the new presets. 

Here's the log for a recent generation. Three Loras are mentioned, and each of them is using a Lora Block Weight preset. However, the fourth Lora, which is using a new preset I just added (which is causing the error) isn't mentioned.

---
                                                                                                                       LoRA Block weight (lora): RoxanneStyle: 0.5 x [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): AgeSlider: -1.0 x [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): HairLength: 3.0 x [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
*** Error running process_batch: C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "C:\Users\silve\Documents\AI Art\__SDUX\modules\scripts.py", line 491, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 309, in process_batch
        loradealer(self, o_prompts ,self.lratios,self.elementals)
      File "C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 571, in loradealer
        if len(lorars) > 0: load_loras_blocks(self, lorans,lorars,multipliers,elements,ltype)
      File "C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 606, in load_loras_blocks
        lbw(lora.loaded_loras[l],lwei[n],elements[n])
    IndexError: list index out of range

---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.32it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.47it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:17<00:00,  1.73it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:17<00:00,  1.44it/s]

**Comment by hako-mikan** [comment]
Are you using with API option?

**Comment by Neverdusk** [comment]
Yes. Is it incompatible with LBW?

My current launch arguments are: --xformers --no-half-vae --api --autolaunch --opt-split-attention

**Comment by hako-mikan** [comment]
Ok.
I got it.
If you want to set preset in API mode in UI.
Use second "LoRA Block Weight" in script in bottom of UI.
I did not assume that some people would use the UI in API mode. This is necessary to use XYZ plot in API mode.

**Comment by Neverdusk** [comment]
I think it works! I used the LBW script, created a new preset in the second extension panel, and then generated an image. No errors, and the Lora actually showed up in the console. 

Is there any way to make it so that the regular LBW panel can work in API mode? I suppose I could disable API mode for LBW, but I tend to leave it on in case other extensions need it.

**Comment by hako-mikan** [comment]
> Is there any way to make it so that the regular LBW panel can work in API mode? 
No.
XYZ plot of this extension uses unusual way, so it needs 2 panels for API mode.
