### ISSUE TITLE
ValueError: could not convert string to float: '1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0'

### ISSUE THREAD

**Issue by geektian** [hako-mikan/sd-webui-lora-block-weight#89]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7f4bc9f7c610>]: ValueError
Traceback (most recent call last):
  File "/root/stable-diffusion-webui/modules/extra_networks.py", line 104, in activate
    extra_network.activate(p, extra_network_args)
  File "/root/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 28, in activate
    unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier
ValueError: could not convert string to float: '1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0'

LoRA Block weight (lora): last-000010: 1.0 x [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): last-000010: 1.0 x [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

**Comment by geektian** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/6f0abbb71a3f29d6df63fed82d5d5e196ca0d4de

**Comment by KoroshM** [comment]
Since there's been a couple questions about this I'll post this here. As a temporary fix for the most simple cases, you can edit these lines in '[WebUI]/extensions-builtin/Lora/extra_networks_lora.py':
28            unet_multiplier = te_multiplier    #float(params.positional[2]) if len(params.positional) > 2 else te_multiplier

31            dyn_dim = None    #int(params.positional[3]) if len(params.positional) > 3 else None

This will get the WebUI to work as normal for anyone who only uses lora weight and this LBW extension, like <lora:name:weight> or <lora:name:weight:LBW>

**Comment by hako-mikan** [comment]
Does that mean it's for people who don't want to use the new format `lbw=`?

**Comment by KoroshM** [comment]
Yes, my comment just makes it work with the previous format.

**Comment by wuyue0509** [comment]
same problem here,

Traceback (most recent call last):
  File "G:\stable-diffusion-webui\modules\extra_networks.py", line 104, in activate
    extra_network.activate(p, extra_network_args)
  File "G:\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 28, in activate
    unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier
ValueError: could not convert string to float: 'OUTS'

**Comment by geektian** [comment]
> same problem here,
> 
> Traceback (most recent call last): File "G:\stable-diffusion-webui\modules\extra_networks.py", line 104, in activate extra_network.activate(p, extra_network_args) File "G:\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 28, in activate unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier ValueError: could not convert string to float: 'OUTS'

lbw=OUTS
