### ISSUE TITLE
Feature Request - Inherit Special Character

### ISSUE THREAD

**Issue by Daniel-Poke** [hako-mikan/sd-webui-lora-block-weight#9]
I've been playing around with this for a little while now and I think I am getting the hang of the syntax. One low hanging fruits I think would be great to implement is a variable syntax that inherits the original weight in the prompt and replaces it over a special character.

For example: `<lora:my_lora:0.8:DEMO>` where `DEMO:X,0,0,0,0,0,0,0,X,X,X,X,0,0,0,0,0`, this would take the `0.8` from the prompt and replace it over the `X` (or whatever you choose) becoming `0.8,0,0,0,0,0,0,0,0.8,0.8,0.8,0.8,0,0,0,0,0` at runtime.

This saves making multiple permutations of the same structure but with only the weight changed identically over the whole array.

Additionally, I thought you could perhaps take this a step further and allow an offset to the replace syntax.

For example: `<lora:my_lora:0.8:DEMO>` where `DEMO:X,0,0,0,0,0,0,0,X,X+0.1,X+0.2,X+0.1,0,0,0,0,0`, this would take the `0.8` from the prompt as previously suggested, but also apply any `+` or `-` offsets placed next to them. So the weights would become `0.8,0,0,0,0,0,0,0,0.8,0.9,1,0.9,0,0,0,0,0` at runtime.

What do you think?

**Comment by hako-mikan** [comment]
Thank you for your valuable suggestion! But it is not easy to implement, give me some time.

**Comment by Daniel-Poke** [comment]
Hey man, I figured I'd give it a crack and raised a PR for this. I also kind of realised something about the base functionality along the way (mentioned in the PR) that makes this feature a bit less useful. But it works none the less, so check it out if you're interested but otherwise feel free to reject the PR and close this Issue.

Keep up the good work! 💪
