### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by OmegaSynthesis** [hako-mikan/sd-webui-lora-block-weight#90]
Not working for some reason

Traceback (most recent call last):
  File "D:\Ai\SD2023\stable-diffusion-webui\modules\extra_networks.py", line 104, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\Ai\SD2023\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 28, in activate
    unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier
ValueError: could not convert string to float: 'XYZ'

**Comment by hako-mikan** [comment]
To use in web-ui 1.5, use following syntax

<lora:"lora name":1:lbw=IN02>  
<lora:"lora name":1:lbw=1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0>  

https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/73
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/78
https://github.com/hako-mikan/sd-webui-lora-block-weight#updates%E6%9B%B4%E6%96%B0%E6%83%85%E5%A0%B1
