### ISSUE TITLE
a very strange thing

### ISSUE THREAD

**Issue by olymax** [hako-mikan/sd-webui-lora-block-weight#91]
A very strange thing happened.
After I enable the block weight, if I enter the weight string (like this <lora:lele_20230624234110:0.8:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1>)in the Lora reference, the entire lora will be invalid, and all the characteristics of the referenced lora model will disappear.

If I keep the original structure (like this <lora:lele_20230624234110:0.8>) in the lora reference, this lora will work no matter if I check the block weight or not.

BTW:I run SD WEBUI on a M1Ultra Mac Studio.

**Comment by hako-mikan** [comment]
What is your web-ui version?

**Comment by olymax** [comment]
version: [v1.5.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/68f336bd994bed5442ad95bad6b6ad5564a5409a)  •  python: 3.10.12  •  torch: 2.0.1  •  xformers: N/A  •  gradio: 3.32.0  •  checkpoint: [e7aab5067d](https://google.com/search?q=e7aab5067d84d2bde9a4e610cbf9e5a2bc4f62d8ecfbe7150628fd20efb5a7d5)

**Comment by hako-mikan** [comment]
To use in web-ui 1.5, use following syntax

<lora:"lora name":1:lbw=IN02>  
<lora:"lora name":1:lbw=1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0>  

https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/73
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/78
https://github.com/hako-mikan/sd-webui-lora-block-weight#updates%E6%9B%B4%E6%96%B0%E6%83%85%E5%A0%B1

**Comment by olymax** [comment]
thank you .
I should read all readme first.
