### ISSUE TITLE
Can not work on webui webui 1.5.1

### ISSUE THREAD

**Issue by DuroCuri** [hako-mikan/sd-webui-lora-block-weight#92]
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
Version: v1.5.1-55-g25004d4e
Commit hash: 25004d4eeef015d8f886c537d3a5a9f54d07898e

Startup time: 37.1s (prepare environment: 23.7s, launcher: 0.1s, import torch: 1.8s, import gradio: 0.6s, setup paths: 0.4s, other imports: 0.5s, list SD models: 0.1s, load scripts: 8.2s, create ui: 1.0s, gradio launch: 0.6s).
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x00000188026805E0>]: ValueError
Traceback (most recent call last):
  File "E:\Novelai\stable-diffusion-webui\modules\extra_networks.py", line 104, in activate
    extra_network.activate(p, extra_network_args)
  File "E:\Novelai\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 28, in activate
    unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier
ValueError: could not convert string to float: 'wear'

As I use lora block weight on webui 1.5 versions, it can not work. But version v1.4.1 do not have this problem.
My tags:
NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
ALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
INS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
IND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0
NF:1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1
face:1,0,0,0,0,0,0,0,0.8,1,1,0.2,0,0,0,0,0
Nface1,1,1,1,1,1,0.2,1,0.2,0,0,0.8,1,1,1,1,1
wear:1,1,1,1,1,0,0.2,0,0.8,1,1,0.2,0,0,0,0,0
bg:1,1,1,1,1,1,0.2,1,0.2,0,0,0.8,1,1,1,0,0
color:1,0,0,0,0,0,0,0,0,0,0,0.8,1,1,1,1,1
INALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0
MIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0
OUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0
OUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1
OUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1
ALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5

**Comment by ivever2** [comment]
me too~~

**Comment by ivever2** [comment]
resolved,for example:
<lora:lora-name:0.8:lbw=face>
add:(lbw=)

**Comment by DuroCuri** [comment]
> resolved,for example: `<lora:lora-name:0.8:lbw=face>` add:(lbw=)

Thanks a lot!

**Comment by DuroCuri** [comment]
> resolved,for example: `<lora:lora-name:0.8:lbw=face>` add:(lbw=)

It can work now. It helps me a lot!
