### ISSUE TITLE
XYZ plot does not work on webui1.5.1

### ISSUE THREAD

**Issue by rainn00o** [hako-mikan/sd-webui-lora-block-weight#94]
I write this prompt, <lora:organic-v10:1:lbw=XYZ>, delete all extensions, but xyz plot still doesn't work, and have no error report.

**Comment by hako-mikan** [comment]
Are you using with API option?

**Comment by rainn00o** [comment]
I used the lbw in auto1111's webui 1.5.1.

**Comment by hisonWarren** [comment]
same problem here

**Comment by RexLeeGrey** [comment]
same problem

**Comment by MemeLord3** [comment]
This issue appears to be caused by https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/96#issue-1841031944
The plugin is reading settings from the second copy of the UI (If you can't see it, you can select it from the scripts dropdown). If you select "LoRA Block Weight" from the scripts dropdown and configure that version of the UI, XYZ appears to work.

**Comment by RexLeeGrey** [comment]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001CD4DF6B010>]: ValueError
Traceback (most recent call last):
  File "D:\AIGC\sd-webui-aki-v4.2\modules\extra_networks.py", line 104, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\AIGC\sd-webui-aki-v4.2\extensions-builtin\Lora\extra_networks_lora.py", line 28, in activate
    unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier
ValueError: could not convert string to float: 'XYZ'

**Comment by MemeLord3** [comment]
> activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001CD4DF6B010>]: ValueError Traceback (most recent call last): File "D:\AIGC\sd-webui-aki-v4.2\modules\extra_networks.py", line 104, in activate extra_network.activate(p, extra_network_args) File "D:\AIGC\sd-webui-aki-v4.2\extensions-builtin\Lora\extra_networks_lora.py", line 28, in activate unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier ValueError: could not convert string to float: 'XYZ'

use the format <lora:yourlora:1:lbw=XYZ>
webui now treats the first 2 parameters as unet weight and te weight so you need to use the named syntax (the 'lbw=' prefix)

There are also 2 copies of the plugins UI being displayed at the moment and it ignores whatever you set in the first copy of the ui.

**Comment by RexLeeGrey** [comment]
LoRA Block weight (lora): Dragon_3：0.4+Mahongfa_5(256)：0.4+Shanshui_10(256)：0.4: 1.0 x [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x00000247CE4DD420>]: ValueError
Traceback (most recent call last):
  File "D:\AIGC\sd-webui-aki-v4.2\modules\extra_networks.py", line 104, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\AIGC\sd-webui-aki-v4.2\extensions-builtin\Lora\extra_networks_lora.py", line 28, in activate
    unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier
ValueError: could not convert string to float: 'NONE'






LoRA Block weight (lora): Dragon_3：0.4+Mahongfa_5(256)：0.4+Shanshui_10(256)：0.4: 1.0 x [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x00000247B163F0A0>]: ValueError
Traceback (most recent call last):
  File "D:\AIGC\sd-webui-aki-v4.2\modules\extra_networks.py", line 104, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\AIGC\sd-webui-aki-v4.2\extensions-builtin\Lora\extra_networks_lora.py", line 28, in activate
    unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier
ValueError: could not convert string to float: '1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0'

**Comment by RexLeeGrey** [comment]
> :lbw=

Thank you, now it works!

**Comment by hako-mikan** [comment]
I couldn't find the cause.
I added debug mode.
Generate XYZ with the conditions you want to use with debug is checked.
Tell me the results you see at the command prompt.

**Comment by MemeLord3** [comment]
In txt2img.py, if you print out 'args', you'll see that all the settings for the "LoRA Block Weight" UI are in there twice. Once for the UI in the top section and again for the UI in the scripts section.

The lora_block_weight.py Script object methods are gertting called with the second copy of the arguments (the args generated from the UI in the scripts section)

There is no issue with XYZ other than the UI being broken and changing 'Disable' to 'XYZ plot' in the first "LoRA Block Weight" section has no effect due to the second "LoRA Block Weight" section overriding the args.

**Comment by LoonLi** [comment]
I met the same problem. Lora block weight worked after adding "lbw=", but it didn't work for XYZ plot, both script and LBW build-in.

There are no error message, and the generated images all shared the same blocked weight. Here is an example I generated with sd-webui 1.6.0:
[https://1drv.ms/i/s!Am69M-1d1c6fg6xhJIWFDe_ZXjNnTw?e=imTA7w](url)

And this one is generated with sd-webui 1.4.0:
[https://1drv.ms/i/s!Am69M-1d1c6fg6xg9T9gN4WS8bvkcw?e=RGP27g](url)

In this case, the XYZ plot started from "ALL", so it generated three identical images with all blocked weights equal to 1. If start XYZ plot from "NONE", it will generate three images with blocked weights equal to 0.

> In txt2img.py, if you print out 'args', you'll see that all the settings for the "LoRA Block Weight" UI are in there twice. Once for the UI in the top section and again for the UI in the scripts section.
> 
> The lora_block_weight.py Script object methods are gertting called with the second copy of the arguments (the args generated from the UI in the scripts section)
> 
> There is no issue with XYZ other than the UI being broken and changing 'Disable' to 'XYZ plot' in the first "LoRA Block Weight" section has no effect due to the second "LoRA Block Weight" section overriding the args.

I checked the "args" variable in txt2img.py, but I didn't find there are duplicated "LoRA Block Weight". 

Without this XYZ plot problem, I feel like the version 1.6.0 is more friendly for me. Hope this issue can be solved.

**Comment by weimo1997** [comment]
呜呜呜，有解决方法吗我也用不了

**Comment by hako-mikan** [comment]
Tell me result with debug checked.

**Comment by LoonLi** [comment]
Thank you for your reply. I will give you the terminal output.

Here is the example that used XYZ plot with prompt S/R to plot MIDD, ALL, and NONE:
```
LoRA Block weight (lora): agnes_digital_r4_lora: 1.0 x [1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
nets
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.99it/s]
LoRA Block weight (lora): agnes_digital_r4_lora: 1.0 x [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
nets
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  8.13it/s]
LoRA Block weight (lora): agnes_digital_r4_lora: 1.0 x [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
nets
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  8.10it/s]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:11<00:00,  5.32it/s]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:11<00:00,  8.12it/s]
```

As you can see, there is no error message, and everything looks good. However, the generated result were all **MIDD**! I also tried to read the codes but I have no idea.

**Comment by LoonLi** [comment]
Thank you for your reply. I will give you the terminal output.

Here is the example that used XYZ plot with prompt S/R to plot lbw equals MIDD, ALL, and NONE:
```
LoRA Block weight (lora): agnes_digital_r4_lora: 1.0 x [1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
nets
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  7.33it/s]
{'isnet': True, 'isxl': False, 'islora': True, 'enable LBW': True, 'registerd': False}                                                                                  | 20/60 [00:02<00:04,  8.17it/s]
LoRA Block weight (lora): agnes_digital_r4_lora: 1.0 x [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
nets
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  8.15it/s]
{'isnet': True, 'isxl': False, 'islora': True, 'enable LBW': True, 'registerd': False}█████████████████████████████████                                                 | 40/60 [00:05<00:02,  8.14it/s]
LoRA Block weight (lora): agnes_digital_r4_lora: 1.0 x [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
nets
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  8.16it/s]
{'isnet': True, 'isxl': False, 'islora': True, 'enable LBW': True, 'registerd': False}██████████████████████████████████████████████████████████████████████████████████| 60/60 [00:08<00:00,  8.15it/s]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:09<00:00,  6.44it/s]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:09<00:00,  8.15it/s]
```
All generated results were blocked by MIDD.

**Comment by LoonLi** [comment]
I have some progress. I think the method `network_apply_weights` in `extensions-builtin/Lora/networks.py` may be responsible for  this issue. It saved the model weights so that images generated in the same batch share the same lora weights. 

I managed to force webui reload model weights for each image, but it seems that this reloading is not complete. I add following code in `extensions/sd-webui-lora-block-weight/scripts/lora_block_weight.py`:
```
def lbw(lora,lwei,elemental):
    elemental = elemental.split(",")
    for name, layer in shared.sd_model.named_modules():
        if not getattr(layer, "network_current_names", None) is None:
            setattr(layer, "network_current_names", ())
    for key in lora.modules.keys():
    # ...
```
With these codes, the images generated by XYZ plot changed, but the result for `lbw=NONE` still remain some features from the lora.

Hope these information can help you.

**Comment by hako-mikan** [comment]
XYZplot cannot be used concurrently with the XYZ plot in the web-ui. 
If other scripts are active in the script section, the XYZ plot of the LoRA Block Weight will be disabled.
