### ISSUE TITLE
Does this plugin support the layering of textual inversion

### ISSUE THREAD

**Issue by aftermath0703** [hako-mikan/sd-webui-lora-block-weight#95]
Textual inversion has an excellent performance in training new concepts, but it also may learn some redundant things, so I want to know whether this plugin supports the layering of textual inversion

**Comment by hako-mikan** [comment]
There is no blocks for textual inversion because the mechanism is different.
Or do you have a textual inversion that interferes with u-net?

**Comment by aftermath0703** [comment]
I just want to know if the text encoding layer can also support blocking, since unet can block the downsampling stage?
I think the process of textual inversion training has also contaminated some other vocabulary. If we can support operations such as adjusting weights, we may achieve better results. :smile:

**Comment by hako-mikan** [comment]
I think that the text encoder is treated as a single layer as BASE and cannot be further divided.
