### ISSUE TITLE
stable diffusion webui extension shows two identical plugins, can you help with the problem?

### ISSUE THREAD

**Issue by WilliamChao** [hako-mikan/sd-webui-lora-block-weight#96]
stable diffusion webui extension shows two identical plugins, can you help with the problem?
<img width="507" alt="Screenshot - 2023-08-08 18 30 32" src="https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/15052053/91041db2-532b-42ef-bd82-2fb605abc68f">

**Comment by hako-mikan** [comment]
This is correct.
Maybe, you web-ui started with API option.
For enabling XYZ plot in API mode, extension need  two identical plugins.
If you want to use UI in API mode, use second one.
