### ISSUE TITLE
doesn't work after update 8/12/2023

### ISSUE THREAD

**Issue by alij8000** [hako-mikan/sd-webui-lora-block-weight#98]
throws a weird error:

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x0000000000AEBE20>]: ValueError
Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\modules\extra_networks.py", line 104, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 28, in activate
    unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier
ValueError: could not convert string to float: 'MIDD'

Steps to reproduce:

just try any damn lora with MIDD block weight(pretty sure other weights including custom weights don't work either).

**Comment by Neverdusk** [comment]
I've also been getting errors where I'm unable to use LBW at all. I have no idea what's causing it. Here's my full error message, though it's a bit different:

---
*** Error running before_process_batch: C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "C:\Users\silve\Documents\AI Art\__SDUX\modules\scripts.py", line 528, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 302, in before_process_batch
        prompts = kwargs["prompts"].copy()
    AttributeError: 'tuple' object has no attribute 'copy'

---
LoRA Block weight (lora): NeverStyleV2A: 0.5 x [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
LoRA Block weight (lora): RoxanneStyle: 0.5 x [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): FemaleToMale: 0.4 x [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  2.99it/s]
LoRA Block weight (lora): NeverStyleV2A: 0.5 x [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
LoRA Block weight (lora): RoxanneStyle: 0.5 x [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): FemaleToMale: 0.4 x [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:08<00:00,  1.23it/s]
*** Error completing request███████████████████████████████████████████████████████████| 30/30 [00:26<00:00,  1.37it/s]
*** Arguments: ('task(eofemhlf7n6i0rp)', '((masterpiece, best quality)), original, absurdres, ((sfw)), <lora:NeverStyleV2A:0.5:lbw=NINALL>, <lora:RoxanneStyle:0.5:lbw=INALL>,\ncreative, interesting, detailed, intricate, colorful,\n(((upper body, facing viewer, looking at viewer))), pov,\n((1boy, solo, a young man, age 20, he is 20 years old)),\n((male, __Character/bodyM__)), <lora:FemaleToMale:0.4:lbw=INALL>,\n((eyes, __Character/characterEyes__)),\n((clothes, __Character/characterClothing__)),\n((simple background, very simple background)), (transparent background, white background),\n((colors, __Concept/conceptColor__)), ((bright))', '(worst quality, low quality), letterboxed, text, letter, logo, signed, signature,\nEasyNegative, VeryBadNegative1.3,AsyncNegative6,\n(((nsfw, nude, huge breasts, gigantic breasts, cleavage, bare legs, partially nude, undressed, underwear, revealing clothes, skimpy clothes))),\n(((feminine, woman, female))), (((Gender-DeFeminize-Negative))),\n(((simple clothes, boring clothes))),\n(((detailed background, complex background))),\n(((monochrome, desaturated)))', [], 20, 16, False, False, 1, 1, 10, -1.0, -1.0, 0, 0, 0, False, 640, 640, True, 0.5, 1.2, 'Latent (nearest-exact)', 10, 0, 0, 18, '', '', [], <gradio.routes.Request object at 0x000001954D586260>, 0, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 2048, 128, True, True, True, False, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000019533061F60>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000019533063A90>, False, '', 0.5, True, False, '', 'Lerp', False, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5\n\nNBASE:0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nNIN01:1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nNIN02:1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nNIN04:1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1\nNIN05:1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1\nNIN07:1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1\nNIN08:1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1\nNMID:0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1\nNOUT03:1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1\nNOUT04:1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1\nNOUT05:1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1\nNOUT06:1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1\nNOUT07:1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1\nNOUT08:1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1\nNOUT09:1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1\nNOUT10:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1\nNOUT11:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0\nNINS:0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1\nNIND:1,1,1,1,0,0,0,1,1,1,1,1,1,1,1,1,1\nNINALL:0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1\nNMIDD:1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1\nNOUTD:1,1,1,1,1,1,1,1,0,0,0,0,1,1,1,1,1\nNOUTS:1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0\nBASENINALL:1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1\n\nMIDDA:1,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0\nMIDDB:1,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0\nMIDDC:1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0\nNMIDDA:1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1\nNMIDDB:1,1,1,1,1,1,0,0,0,0,1,1,1,1,1,1,1\nNMIDDC:1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1\nINA:0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0\nINB:0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False, False, False, 0, 1, 1, 0, 0, 0, 0, False, 'Straight Abs.', 'Flat', False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, 50, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5\n\nNBASE:0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nNIN01:1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nNIN02:1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nNIN04:1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1\nNIN05:1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1\nNIN07:1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1\nNIN08:1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1\nNMID:0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1\nNOUT03:1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1\nNOUT04:1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1\nNOUT05:1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1\nNOUT06:1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1\nNOUT07:1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1\nNOUT08:1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1\nNOUT09:1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1\nNOUT10:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1\nNOUT11:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0\nNINS:0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1\nNIND:1,1,1,1,0,0,0,1,1,1,1,1,1,1,1,1,1\nNINALL:0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1\nNMIDD:1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1\nNOUTD:1,1,1,1,1,1,1,1,0,0,0,0,1,1,1,1,1\nNOUTS:1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0\nBASENINALL:1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1\n\nMIDDA:1,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0\nMIDDB:1,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0\nMIDDC:1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0\nNMIDDA:1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1\nNMIDDB:1,1,1,1,1,1,0,0,0,0,1,1,1,1,1,1,1\nNMIDDC:1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1\nINA:0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0\nINB:0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False) {}
    Traceback (most recent call last):
      File "C:\Users\silve\Documents\AI Art\__SDUX\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\silve\Documents\AI Art\__SDUX\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "C:\Users\silve\Documents\AI Art\__SDUX\modules\txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "C:\Users\silve\Documents\AI Art\__SDUX\modules\processing.py", line 673, in process_images
        res = process_images_inner(p)
      File "C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "C:\Users\silve\Documents\AI Art\__SDUX\modules\processing.py", line 866, in process_images_inner
        text = infotext(n, i)
      File "C:\Users\silve\Documents\AI Art\__SDUX\modules\processing.py", line 726, in infotext
        all_prompts[iteration * p.batch_size:(iteration + 1) * p.batch_size] = p.prompts
    TypeError: 'tuple' object does not support item assignment

---

**Comment by hako-mikan** [comment]
To use in web-ui 1.5, use following syntax

<lora:"lora name":1:lbw=IN02>
<lora:"lora name":1:lbw=1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0>

https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/73
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/78
https://github.com/hako-mikan/sd-webui-lora-block-weight/issues/93
https://github.com/hako-mikan/sd-webui-lora-block-weight#updates%E6%9B%B4%E6%96%B0%E6%83%85%E5%A0%B1

**Comment by alij8000** [comment]
> To use in web-ui 1.5, use following syntax
> 
> <lora:"lora name":1:lbw=IN02> <lora:"lora name":1:lbw=1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0>
> 
> #73 #78 #93 https://github.com/hako-mikan/sd-webui-lora-block-weight#updates%E6%9B%B4%E6%96%B0%E6%83%85%E5%A0%B1

Yup, thanks for clearing it up for me :D! and thanks for the amazing extension.
