### ISSUE TITLE
 AttributeError: 'tuple' object has no attribute 'copy'

### ISSUE THREAD

**Issue by Kuron88** [hako-mikan/sd-webui-lora-block-weight#99]
*** Error running before_process_batch: D:\sd.webui\webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "D:\sd.webui\webui\modules\scripts.py", line 527, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "D:\sd.webui\webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 302, in before_process_batch
        prompts = kwargs["prompts"].copy()
    AttributeError: 'tuple' object has no attribute 'copy'

**Comment by mildfever** [comment]
Getting the same error.

vlad UI: d4b5c487
Firefox: 116.0.2
RTX 3060

**Comment by ThisisLandu** [comment]
same error
rtx4090
version: [v1.5.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/68f336bd994bed5442ad95bad6b6ad5564a5409a)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint: [b32b6c4993](https://google.com/search?q=b32b6c4993f760702e8794590ee1a1c1ae85a2dd77f0fd25dd56d64247583a9b)

**Comment by hako-mikan** [comment]
Disable dynamic prompt.
https://github.com/adieyal/sd-dynamic-prompts/issues/593

**Comment by yamosin** [comment]
> Disable dynamic prompt. [adieyal/sd-dynamic-prompts#593](https://github.com/adieyal/sd-dynamic-prompts/issues/593)

I had the same problem and the problem persisted after disabling the Dynamic prompt extension - but it no longer pops up errors
Console message seem right but lora is not apply
![image](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/65278942/fe5cabee-de20-4cb9-854f-cc97b1a58397)
This is lora without lbw
```
1girl,loli,<lora:ArknightsShamare_10:0.7>
Negative prompt: verybadimagenegative_v1.3,
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1287901600, Size: 512x512, Model hash: b2bd65469b, Model: 萝心_3874.fp16, Clip skip: 2, ENSD: 31337, Token merging ratio: 0.5, NGMS: 5, Lora hashes: "ArknightsShamare_10: b245f4b8c42e", TI hashes: "verybadimagenegative_v1.3: d70463f87042", Discard penultimate sigma: True, Version: v1.5.1, Hashes: {"vae": "df3c506e51", "embed:verybadimagenegative_v1.3": "d70463f870", "lora:ArknightsShamare_10": "ba95c0c7bc", "model": "b2bd65469b"}
```
![image](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/65278942/05200e1b-1663-4a0b-a492-aba44d8483c1)

And this is lora double the value and lbw=ALL0.5 , same seed
```
1girl,loli,<lora:ArknightsShamare_10:1.5:lbw=ALL0.5>
Negative prompt: verybadimagenegative_v1.3,
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1287901600, Size: 512x512, Model hash: b2bd65469b, Model: 萝心_3874.fp16, Clip skip: 2, ENSD: 31337, Token merging ratio: 0.5, NGMS: 5, Lora hashes: "ArknightsShamare_10: b245f4b8c42e", TI hashes: "verybadimagenegative_v1.3: d70463f87042", Discard penultimate sigma: True, Version: v1.5.1, Hashes: {"vae": "df3c506e51", "embed:verybadimagenegative_v1.3": "d70463f870", "lora:ArknightsShamare_10": "ba95c0c7bc", "model": "b2bd65469b"}
```
![image](https://github.com/hako-mikan/sd-webui-lora-block-weight/assets/65278942/09adbedd-cb1a-4130-8db0-d76acf1bf5e3)

And i tried without lbw, and its normally pops up a error
`ValueError: could not convert string to float: 'ALL0.5'`

**Comment by hako-mikan** [comment]
@yamosin 
Issue on dynamic prompt is fixed so I close this issue.
If you get another problem, make another issue.
